Add ability to update and create quotes via json schema
HedvigInsurance/hedgehog pull request #238
Opened 2020-09-30 08:09 UTC by vonElfvin

Update house example:
![image](https://user-images.githubusercontent.com/20777544/94659710-ffb90480-0304-11eb-8b52-fa74081dd7a6.png)

Create apartment example:
![image](https://user-images.githubusercontent.com/20777544/94659760-12333e00-0305-11eb-85ff-f49ca9a21005.png)

2020-10-06 07:52 UTC, vonElfvin commented on shared/hedvig-ui/json-schema-form.tsx
> +  console.log(formData)
No console log

2020-10-06 07:52 UTC, vonElfvin commented on shared/hedvig-ui/json-schema-form.tsx
> +  text.charAt(0).toUpperCase() + text.substring(1).replace(/(\B[A-Z])/g, ' $1')
Move to util

2020-10-06 07:52 UTC, vonElfvin commented on src/components/member/tabs/index.js
> +import { Quotes as QuotesV2 } from 'components/member/tabs/quote-tab-v2'
Remove

2020-10-06 07:52 UTC, vonElfvin commented on src/components/member/tabs/quote-tab/index.tsx
> -import { useQuotes } from 'graphql/use-quotes'
Clean up this one

2020-10-06 07:52 UTC, vonElfvin commented on src/graphql/get-quotes.graphql
> +          street
This should be able to be removed now

2020-10-06 08:52 UTC, vonElfvin commented on src/graphql/get-quotes.graphql
> +          street
I decided not to remove it for other usages. I'll clean this up all the way when we see that this works.

2020-10-06 09:15 UTC, palmenhq requested changes
I think you may be lookin for this package :) https://www.npmjs.com/package/@types/json-schema

2020-10-06 09:15 UTC, palmenhq commented on src/utils/quote.tsx
> +  createdAt.setSeconds(quote.validity!)
I see three issues here.

1. I'm pretty sure `setSeconds` i supposed to set the second of the minute, meaning it should be between 0-59. An easier way out i think would be to use `quote.createdAt + quote.validity` and pass that to the constructor, right?

2. I believe the `createdAt` and `validity` timestamps are in seconds right? JavaScript expects all timestamps to be in milliseconds, so assuming the timestamps are in seconds this won't work. You need to multiply them both with `1000` (i'm slightly unsure about this one but i'm kinda sure)

3. What if `validity` is null? We're disregarding that case now.

2020-10-06 09:15 UTC, palmenhq commented on src/utils/quote.tsx
> +export const expiredPredicate = (quote: Quote) => {
Please challenge this, i love the word predicate. But i think its mostly used within typing (in the context of "put a predicate here") and i think for these functions could rather be named `isSignedOrExpired` and `isExpired`. Both work though :)

2020-10-06 15:35 UTC, vonElfvin commented on src/utils/quote.tsx
> +  createdAt.setSeconds(quote.validity!)
I moved this from another file, haven't really considered it tbh. I'll check it out though

2020-10-06 15:35 UTC, vonElfvin commented on src/utils/quote.tsx
> +export const expiredPredicate = (quote: Quote) => {
Same here, I just moved this. Can look into it though

2020-10-06 15:53 UTC, vonElfvin commented on src/utils/quote.tsx
> +  createdAt.setSeconds(quote.validity!)
But yea, that line looks off to me in its entirety. I'll just remove it tbh.

2020-10-06 15:54 UTC, vonElfvin commented on src/utils/quote.tsx
> +export const expiredPredicate = (quote: Quote) => {
I agree with you, isSigned etc. is way more clear. Didn't really understand what it did with the word "predicate"

2020-10-06 15:55 UTC, vonElfvin commented on src/utils/quote.tsx
> +export const expiredPredicate = (quote: Quote) => {
However, I'm pretty sure it's another @palmenhq criticises younger @palmenhq here 😉

2020-10-06 15:58 UTC, vonElfvin commented on src/graphql/use-update-quote-by-schema.tsx
> +): MutationFunctionOptions<
Didn't know you could do that, been trying multiple times but never seem to figure out where to put the `: Params` declaration! Really neat :)

2020-10-06 15:59 UTC, vonElfvin commented on shared/hedvig-ui/json-schema-form.tsx
> +  initialFormData?: object
unknown won't work at a later stage, but Record is what I'm looking for here :)

2020-10-06 16:00 UTC, vonElfvin commented on src/components/member/tabs/quote-tab/update-quote-form.tsx
> +      quote.memberId!!,
Kotlin I guess 🤷

2020-10-06 16:01 UTC, vonElfvin commented on src/graphql/use-get-schema-for-contract-type.tsx
> +  object,
used `JSONSchema7` :)

2020-10-07 06:40 UTC, rasmusguterstam commented on src/components/member/tabs/contracts-tab/agreement/CreateQuoteFromAgreement.tsx
>            .includes(agreement.id) && !loadingQuotes ? (
Perhaps this could be defined as a const earlier on, e.g. `const quoteAlreadyExists = ...` to make it more readable? 🙃

2020-10-07 06:59 UTC, rasmusguterstam commented on src/graphql/use-create-quote-for-member-by-schema.tsx
> +> => {
I've been thinking about this approach as to how we write query-helpers. Might just be me, but using a variable helper (`get...Options`) always feels a bit awkward - why require this intermediate step? Why not use lazy queries and integrate it? 

I tried a variant on this [here](https://github.com/HedvigInsurance/hedgehog/pull/234/files?file-filters%5B%5D=.js&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx#diff-248b7e23976c26724393abc9b4e64eb2), could this be a valid approach or am I missing something obvious? 🧐

2020-10-07 08:59 UTC, vonElfvin commented on src/graphql/use-create-quote-for-member-by-schema.tsx
> +> => {
The reason being that the options for the mutation are usually not super simple to build. For example the one you sent, knowing what defaults are reasonable etc. is not always obvious for the consumer of the mutation. 

For this case in particular the 

```
schemaData: {
   id: schema.$id,
   ...formData,
```
will be a bit hard to figure out as a consumer unless it is centralised like this.

Also having relevant refetchQueries centralised makes sense as well, like for quotes for the particular member in this case.

2020-10-07 09:03 UTC, vonElfvin commented on src/components/member/tabs/contracts-tab/agreement/CreateQuoteFromAgreement.tsx
>            .includes(agreement.id) && !loadingQuotes ? (
Makes sense, I'll move it :)

2020-10-07 09:03 UTC, palmenhq reviewed
Amaze! Just one detail i think is worth fixing

2020-10-07 09:03 UTC, palmenhq commented on shared/hedvig-ui/json-schema-form.tsx
> +}
Idk why my comment disappeared but i really dislike this way of mutating the existing object. Rather, we should make a copy of it and return that new error as i suggested before.

2020-10-07 09:11 UTC, vonElfvin commented on shared/hedvig-ui/json-schema-form.tsx
> +}
Oh yea, I missed that part 🤦 Fixed it now!

2020-10-07 09:12 UTC, palmenhq submitted a review, later dismissed
![](https://media3.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy.gif)

2020-10-08 15:30 UTC, merged