Implement Hedvig CLI
HedvigInsurance/hedgehog pull request #285
Opened 2021-02-25 17:47 UTC by rasmusguterstam

## What?
- Adds Hedvig CLI - a "spotlight"-feature for H.ope which enables centralized shortcuts and component-specific actions.
- Adds the hook `useCommandLine()` which in turn provides:
  - `useAction(actions: CommandLineActions[])`: Enables a component to register centralized shortcuts
  - `isHinting: boolean`: Enable shortcut-hinting on component-level
  - `setBlocked(value: boolean)`: Block the CLI shortcuts while, for example, input fields are focused
- Components can register specific actions to the centralized CLI. These actions can then be called centrally by the CLI (either explicitly from the spotlight feature, or using the specified shortcut).

## Why?
- This is one result of the maker's week project _Alfred_, which aims to speed up and facilitate the usage of H.ope
- It's pretty sweet with shortcuts
- It's pretty sweet with shortcut-hints
- It's difficult to remember all shortcuts, so a slick, interactive interface which assists you is pretty sweet
- It's nice to have a centralized unit which can resolve component specific actions
- It's nice to have a standardized interface to easily implement shortcuts across hedgehog

## Example of how it works (pseudo)

```javascript

export const MemberPage: React.FC = () => {
    const { useAction, isHinting } = useCommandLine()

    ...

    useAction([
        {
             label: `${memberName}'s contracts`,
             keysHint: ['⌥', '4'],
             keys: [KeyCode.Option, KeyCode.4],
             onResolve: () => {
                history.push(`/members/${memberId}/${panes[4].tabName}`)
             },
        },
        {
             label: `Send an email to ${member.email}`,
             keysHint: ['⌥', 'E'],
             keys: [KeyCode.Option, KeyCode.E],
             onResolve: () => {
                window.open(`mailto:${member.email}`)
             },
        },
    ])

    ...

    return <>
        ...
        <Tab>{isHinting ? 'Contracts (C)' : 'Contracts'}</Tab>
        ...
    </>
} 

```

## Optional screenshots

![image](https://user-images.githubusercontent.com/51323202/109193328-88df4500-7798-11eb-93a2-cc6af16f9ce3.png)

https://user-images.githubusercontent.com/51323202/109193384-97c5f780-7798-11eb-94de-614601ee0469.mov

## Disclaimer
It was a bumpy ride to manage states globally, so we went for some mixture of refs & state to keep everything updated. It works as supposed to, but if anyone sees anything weird and knows a better implementation, I'm all ears! 🤓

## Optional checklist
- [x] Updated `src/changelog.ts`
- [x] Codescouted
- [x] Unit tests written (partially)
- [x] Tested locally

2021-02-26 11:06 UTC, palmenhq requested changes
Hello, Palmen's Nit ™️ is back! Good stuff though 😍 Really awesome feature and over all really awesome work on this!

2021-02-26 11:33 UTC, palmenhq reviewed
One more thought... We have a lot of option/alt key commands here. Maybe we should try to use ctrl/command more? Because option/alt is used to type right? Maybe not so common for letters but definitely on numbers (ie alt + 2 for `@` on swedish keyboard). I guess in the chat that wouldn't be an issue since we use the `blocking` feature of CommandLine, but won't we need to do that for every form field throughout hope? For example, how does it work to change the email address of the member now? An option could be to always check if there's any focused form field on the page. Normally I don't like querying the DOM while using react but i think this might be the exception, as this spotlight is a global thing. Something like this might do the trick:

```ts
const shouldBlockCli = () =>
  [...document.querySelectorAll('input, textarea')]
    .includes(document.activeElement)
```

2021-02-26 12:02 UTC, rasmusguterstam commented on shared/hedvig-ui/radio.tsx
> +    value: any
@vonElfvin, but yeah that makes sense!

2021-02-26 12:04 UTC, rasmusguterstam commented on src/components/claims/claim-details/components/ClaimPayments.tsx
> -                  {totalDeductible.toFixed(2)}&nbsp;
Yes def!

2021-02-26 12:05 UTC, rasmusguterstam commented on src/components/member/index.js
> +    },
Good point, I implemented it for makers week demo but we should probably keep special actions like these to a minimum for now!

2021-02-26 12:06 UTC, rasmusguterstam commented on src/components/member/index.js
> +                  )
Really good point!

2021-02-26 12:06 UTC, rasmusguterstam commented on src/components/questions/filter.tsx
> +  }
@vonElfvin

2021-02-26 12:07 UTC, rasmusguterstam commented on src/utils/hooks/command-line-hook.tsx
> +export const useCommandLine = () => React.useContext(CommandLineContext)
Yeah I thought about that as well. Will look into this!

2021-02-26 12:08 UTC, rasmusguterstam commented on src/components/questions/filter.tsx
>    Denmark,
@vonElfvin

2021-02-26 12:13 UTC, rasmusguterstam commented
@palmenhq I've missed Palmen's Nit ™️, glad to have you back! 😄 I think you make a really good point using ctrl instead. As you noticed, we used `blocked` to limit the CLI but yes, that requires active blocking. However, another reason for blocking is to not disturb the `keydown` event. It seems as if our keyboard listener is active at the same time an input is listening, it lags brutally. Could probably be fixed by tweaking the implementatiom though, so I'll look into it!

2021-02-26 12:49 UTC, vonElfvin commented on shared/hedvig-ui/radio.tsx
> +    value: any
This is not allowed with a React.FC 

https://stackoverflow.com/questions/53958028/how-to-use-generics-in-props-in-react-in-a-functional-component

https://stackoverflow.com/questions/59947787/generictype-in-react-fcpropst

2021-02-26 12:54 UTC, vonElfvin commented on shared/hedvig-ui/radio.tsx
> +    value: any
I put `string | number` to make it a bit more robust

2021-02-26 12:58 UTC, vonElfvin commented on src/components/member/index.js
> +                  )
Didn't know history.replace even existed, because the " do we want the back button to work between tabs or not really" it the answer is **not** which is why we fixed the "back to claim" keybind

2021-02-26 16:18 UTC, vonElfvin commented on src/components/member/index.js
> +                  )
Thus I used replace which is a lot better here

2021-03-04 09:23 UTC, rasmusguterstam commented on src/utils/hooks/command-line-hook.test.tsx
> +    expect(wrapper.children().find(CommandLineComponent).length).toEqual(1)
Haha yeah definitely! First time exploring these assertions, just moved on on the first approach that worked 😅

2021-03-04 10:08 UTC, rasmusguterstam commented on src/utils/hooks/command-line-hook.tsx
> +            setValue(target.value)
Yeah the `@ts-ignore` were just a lack of effort during makers week haha. I've fixed that and clarified a bit now, but the point is to check for a `nbsp` (when opening the prompt) and `space` (as the first character).

2021-03-04 10:09 UTC, rasmusguterstam commented on src/utils/hooks/command-line-hook.tsx
> +          placeholder="What can I help you with?"
I know right!!

2021-03-11 18:42 UTC, rasmusguterstam commented on src/utils/hooks/command-line-hook.tsx
> +export const useCommandLine = () => React.useContext(CommandLineContext)
So the point of extracting a "custom hook" (i.e. `useAction`) in this case is to wrap a rather nasty `useEffect` which manages mounting & unmounting for the component which calls it. So it gets pretty complex to implement something like you suggest. However, I have renamed it to `registerActions` now instead, so it might not be as much of that "hook-y" feeling haha

2021-03-15 08:45 UTC, palmenhq commented on src/utils/hooks/command-line-hook.tsx
> +export const useCommandLine = () => React.useContext(CommandLineContext)
Maybe i'm missing something but i understand it gets complex if you allow changing of the actions (ie passing a dynamic array) but wouldn't using a "static" array make it even easier? No need to place the actions in a state even. But i haven't tried it so maybe not

2021-03-15 14:14 UTC, palmenhq reviewed
Nice! So close now

2021-03-18 13:49 UTC, palmenhq reviewed
Last nit i promise!

![](https://media.giphy.com/media/3ohjV6cUjy3wEtaOOs/source.mp4)

2021-03-18 13:49 UTC, palmenhq commented on src/components/shared/navigation/sidebar/VerticalMenu.tsx
> +    locations.forEach((location) => {
what happens now if you have 2 matches?

2021-03-18 13:49 UTC, palmenhq commented on src/components/shared/navigation/sidebar/VerticalMenu.tsx
> +      })
what happens now if you have 2 matches? I'm interpreting this code as that it'd set the last match as the latest claim, but on the way also call `setLatestClaim` on all other matches. I think the neatest way to do it this way is to use an actual `for` loop with a `break`/`continue` statement:

```ts
    for (const locationIndex in locations) {
      const match = matchPath(locations[locationIndex], {
        path: '/claims/:claimId/members/:memberId',
        exact: true,
        strict: false,
      })

      if (!match) {
        continue
      }

      const { memberId, claimId } = match.params as LatestClaim

      setLatestClaim({
        memberId,
        claimId,
        location,
      })
      break
    }
```

untested but you get the point

2021-03-22 09:33 UTC, palmenhq approved these changes
Awesome! Maybe add this to the change log?

2021-03-25 07:37 UTC, merged

2021-03-29 16:28 UTC, vonElfvin reviewed
Call me Mr. Nit ™️

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +    if (isOptionPressed && isSpacePressed) {
Shouldn't this be "isControlPressed" since it seems to be using control now?

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +      >
Styled components are nice

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +  }, [])
Is this needed given the default is 0 above?

2021-03-29 16:28 UTC, vonElfvin commented on src/components/shared/navigation/sidebar/VerticalMenu.tsx
> +      keysHint: ['CTRL', '←'],
There is a better backspace icon I think? ⌫

2021-03-29 16:28 UTC, vonElfvin commented on src/components/shared/navigation/sidebar/VerticalMenu.tsx
> +      keys: [KeyCode.Control, KeyCode.C],
May as well had a "KeyHint" object with strings in it

2021-03-29 16:28 UTC, vonElfvin commented on src/components/member/tabs/index.tsx
> +    menuItem: `Member ${isHinting ? '(1)' : ''}`,
Since these will become wider when hinting maybe we can minimize that a bit by adding more spaces or making the width "fixed" (maybe fraction wise is available?)

2021-03-29 16:28 UTC, vonElfvin commented on src/components/member/index.js
> +        history.push(`/members/${memberId}/${panes[0].tabName}`)
I'd say make this into a helper function and use it, `replace` is the key change. And repeating this line is a bit tedious   
```
history.replace(
  `/members/${memberId}/${panes[activeIndex].tabName}`,
)
```

2021-03-29 16:28 UTC, vonElfvin commented on src/components/member/index.js
> +        history.push(`/members/${memberId}/${panes[0].tabName}`)
Or actually we should just change the active index and it should solve itself really. `setActiveIndex(0)` would yield the same result without using history every time and using `replace`

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +      .slice(0, 3)
This makes a lot of sense. However, to encourage (and help) exploration, maybe we should always include the whole. Including for `''` and for searches. Or maybe this is a future thing if the "scrolling" is tricky to do
```
const getSearchResult = (query: string) => {
    return actions
      .filter((item) => {
        return item.label.toLowerCase().includes(query.toLowerCase())
      })
  }
```

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +    setShowCommandLine(false)
Maybe a low risk, but are we making sure we "unfocus" the CLI after closing? Maybe it just dissapears from the dom 🤷

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +  }, [isOptionPressed, isSpacePressed])
isControlPressed

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +          removeAction(newAction.label)
Removing based on a label is a bit weird, on the same time having multiple with the same label is unlikely

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/key-press-hook.tsx
> +  F24: 135,
Thinking of it maybe anything above F12 is a bit unlikely 😄

2021-03-29 16:28 UTC, vonElfvin commented on src/utils/hooks/command-line-hook.tsx
> +        action.keys.filter((key) => !keys.includes(key)).length === 0
For let's say `CTRL-C`, ff we want to not allow things like `CTRL-O-P-L-C` to work we also need to check the lengths:
`const match = action.keys.length === keys.length && action.keys.filter((key) => !keys.includes(key)).length === 0`