Feature/handle employees
HedvigInsurance/hedgehog pull request #359
Opened 2021-08-16 09:07 UTC by cpiehl1

# Jira Issue: [MX-221]

## What?
- View for viewing, and editing employees.

## Why?
- So that this no longer has to be done manually in the database

## Optional screenshots

https://user-images.githubusercontent.com/35833651/129539180-ef85763d-9228-44aa-9547-6c1077f0e2d9.mov

## Optional checklist
- [x] Updated `src/changelog.ts`
- [x] Codescouted
- [ ] Unit tests written
- [x] Tested locally

2021-08-16 12:41 UTC, rasmusguterstam commented on schema.graphql
> +enum Role {
Although I like that it's clean, we might want to add a prefix, e.g.:
```suggestion
enum EmployeeRole {
```

2021-08-17 09:08 UTC, rasmusguterstam requested changes

2021-08-17 09:08 UTC, rasmusguterstam commented on src/features/tools/employees/components/EmployeeTable.tsx
> +      {(employees.loading && <Card span={1}>Loading employees...</Card>) ||
Use a `<LoadingMessage paddingTop={'25vh'} />` instead of plain text

2021-08-17 09:08 UTC, rasmusguterstam commented on src/features/tools/employees/components/EmployeeTable.tsx
> +          <Card span={1}>No employees exist in the database</Card>
Similar here, but instead something like:

```javascript
<StandaloneMessage paddingTop="25vh">
  No employees exist in the database
</StandaloneMessage>
```

2021-08-17 09:08 UTC, rasmusguterstam commented on src/features/tools/employees/index.tsx
> +export const EmployeesComponent: React.FC<{ scopes: readonly string[] }> = (
Any specific reason why we specify `readonly`?

2021-08-17 09:08 UTC, rasmusguterstam commented on src/features/tools/employees/index.tsx
> +  scopes,
```suggestion
  { scopes },
```

And then just go for `scope` in the rest of the file, instead of `scope.scope`

2021-08-18 07:13 UTC, rasmusguterstam approved these changes
Let's goooo 🔥👑

2021-08-20 06:26 UTC, anthansson commented on schema.graphql
> +enum Role {
It's removed all together and treated as string now!

2021-08-23 14:16 UTC, vonElfvin approved these changes
🔥 !

2021-08-23 14:34 UTC, merged