Feature/campaign code types
HedvigInsurance/hedgehog pull request #365
Opened 2021-08-30 14:27 UTC by cpiehl1

# Jira Issue: [MX-251]

## What?
- Add code types to campaign codes

## Why?
- To not have to manage this separately

## Optional screenshots

https://user-images.githubusercontent.com/35833651/131354923-5029e7be-077c-4502-bf00-f642477074ad.mov

## Optional checklist
- [x] Updated `src/changelog.ts`
- [x] Codescouted
- [ ] Unit tests written
- [x] Tested locally

2021-08-31 07:52 UTC, rasmusguterstam commented on src/features/tools/campaign-codes/utils.tsx
> +}
Really nice!!

2021-08-31 07:55 UTC, rasmusguterstam requested changes
Let's gooo! The only thing I'm thinking is whether you could Camel Case the enums, e.g. "PROPERTY PARTNER" -> "Property Partner"?

2021-08-31 08:42 UTC, cpiehl1 commented
@rasmusguterstam Done!

2021-08-31 09:39 UTC, rasmusguterstam approved these changes

2021-09-01 09:08 UTC, joacimastrom commented on src/features/tools/campaign-codes/components/CampaignCodeTable.tsx
> +                  <Table.Cell textAlign={'center'}>{campaignCode}</Table.Cell>
I'd make a styled component for this 
```
const CenteredCell = styled(Table.Cell)`
    text-align: center;
`
```

2021-09-01 09:14 UTC, joacimastrom commented on src/features/tools/campaign-codes/utils.tsx
> +        label: (value as string)
```suggestion
        label: (value as string).replace("_", " ").toUpperCase()
```

2021-09-01 09:17 UTC, joacimastrom approved these changes
Looks good, well done!

2021-09-01 09:25 UTC, cpiehl1 commented on src/features/tools/campaign-codes/components/CampaignCodeTable.tsx
> +                  <Table.Cell textAlign={'center'}>{campaignCode}</Table.Cell>
Good point!

2021-09-02 12:35 UTC, merged