IP-25: Kill auth redux
HedvigInsurance/hedgehog pull request #366
Opened 2021-08-30 15:42 UTC by rasmusguterstam

# Jira Issue: [IP-25](https://hedvig.atlassian.net/browse/IP-25)

## What?
- Remove auth state from redux (which is the final piece, woho!)
- Add a `useScopes` hook, which resolves employee scopes from a cookie. This cookie is set every time an access token is recieved and stored, from which the scopes are retrieved. The Access Token and Refresh Token are both `HttpOnly`, which is a good thing, but this means that we can't decode the JWT and retrieve the scopes directly. An important aspect to consider in this approach is that the scopes easily are manipulated on the client side, and should therefore _only_ be used as an assisting tool to make a nice UX (e.g. the employee management tool). The final authentication should, as always, happen server-side.

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [x] Codescouted
- [ ] Unit tests written
- [x] Tested locally

2021-08-31 07:40 UTC, palmenhq requested changes
I happened to notice this and figured i'd give my two cents! AWESOME to see redux is finally going to 🔥 😍 i'm assuming there's another ticket for 🔪 the other parts

hope y'all are alright over there, tell the others i said hi!

2021-08-31 07:40 UTC, palmenhq commented on src/routes/PrivateRoute.tsx
> +        if (error || !data?.me) {
what if there's a network glitch (ie the member lose wifi for a couple of minutes)? should you really log the person out in that case? Maybe you could just check the error type and status code and retry with some kind of backoff

2021-08-31 07:40 UTC, palmenhq commented on src/utils/auth.ts
> +}
i think you should use a "proper" cookie parser lib actually, this feels a little shaky to diy

2021-08-31 07:40 UTC, palmenhq commented on src/utils/auth.ts
> +    console.log(cookie)
🙈

2021-08-31 07:40 UTC, palmenhq commented on src/server/auth.ts
> +import jwt_decode from 'jwt-decode'
I think you've been in python-land too much lately 🐍

2021-08-31 07:40 UTC, palmenhq commented on src/utils/auth.ts
> +  const { data, loading, error } = useGetMeQuery()
if we use the `getMe` query here anyways can't we just use the scopes from that result or so? I can't see the back-office repo anymore but it should be available in the [gatekeeper response](https://github.com/HedvigInsurance/gatekeeper/blob/91800e9343c20bd102d41af4b112937390b23c98/src/main/kotlin/com/hedvig/gatekeeper/GatekeeperApplication.kt#L186-L192) so it shouldn't be too hard to read from there instead

2021-08-31 09:20 UTC, rasmusguterstam commented on src/server/auth.ts
> +import jwt_decode from 'jwt-decode'
This seems to be the only way for this package... 😩

2021-08-31 09:25 UTC, rasmusguterstam commented
> I happened to notice this and figured i'd give my two cents! AWESOME to see redux is finally going to 🔥 😍 i'm assuming there's another ticket for 🔪 the other parts
> 
> hope y'all are alright over there, tell the others i said hi!

@palmenhq What a lovely surprise - we were actually just talking about the PRs during standup when someone said "...oh, Palmen just reviewed one of those" 😄 

Hope (🤪) you're alright and that you're killing it at the new place!! 🔥

2021-08-31 09:25 UTC, rasmusguterstam commented
And as always - great feedback, cheers!!

2021-08-31 11:17 UTC, palmenhq commented on src/server/auth.ts
> +import jwt_decode from 'jwt-decode'
I just ment the `snake_case` :D

2021-08-31 11:18 UTC, palmenhq commented
Haha! all is good here thanks, cheers!

2021-08-31 11:53 UTC, rasmusguterstam commented on src/server/auth.ts
> +import jwt_decode from 'jwt-decode'
oh god

2021-09-01 07:10 UTC, joacimastrom commented on src/App.tsx
> -                          <Routes.PrivateRoute
Don't we still need PrivateRoute but with an implementation that uses the `getMeQuery`?

2021-09-01 08:22 UTC, palmenhq commented on src/App.tsx
> -                          <Routes.PrivateRoute
Or maybe something that hides everything behind a loader (similar to before) or white page before we know they're not authenticated, to avoid a content flash.

2021-09-01 09:26 UTC, joacimastrom commented on src/App.tsx
> -                          <Routes.PrivateRoute
Looked into it and realised ApolloClient checks auth already so maybe PrivateRoute is not necessary after all. WDYT?

2021-09-01 09:30 UTC, joacimastrom approved these changes
Looks good! Approved assuming it's tested ☺️

2021-09-01 09:46 UTC, palmenhq commented on src/App.tsx
> -                          <Routes.PrivateRoute
Yes from a security perspective i don't think it matters, but we'll still get the content flash if you try to access the system without being authenticated.

2021-09-01 09:55 UTC, vonElfvin approved these changes
Wow 😍 I don't think content flash is an issue since it'll:
1. Either be 0 data since all requests require authentication
2. If there is content it'll be cached at most, but arguably that is impossible since if you are logged out you leave the site by design

2021-09-01 09:55 UTC, vonElfvin commented on schema.graphql
> +  me: Me
With this we probably need to make a "aligned deployment" with back-office+hedgehog at the same time, not the end of the world but something to be aware of

2021-09-01 09:55 UTC, vonElfvin commented on src/App.tsx
>                              store={store}
Guess we can remove store here?

2021-09-01 09:55 UTC, vonElfvin commented on src/components/claims/claim-details/components/ClaimNotes.tsx
> +              handlerReference: data?.me?.email ?? '',
For future reference I guess this should not be sent from the client, but rather extracted in the mutation inside back-office

2021-09-01 09:55 UTC, vonElfvin commented on src/features/tools/employees/index.tsx
> +  const scopes = data?.me?.scopes ?? []
In the future I think we'll have to have scopes in some context for easy access, but this will do the trick for sure! 🥇

2021-09-01 10:48 UTC, rasmusguterstam commented on src/components/claims/claim-details/components/ClaimNotes.tsx
> +              handlerReference: data?.me?.email ?? '',
Yeah def agree!

2021-09-01 14:03 UTC, palmenhq approved these changes
Good stuff 🔥

2021-09-02 13:55 UTC, merged