Update payout form with hedvig ui and useForm
HedvigInsurance/hedgehog pull request #368
Opened 2021-09-02 06:37 UTC by maxplt

# Jira Issue: [IP-27](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-27)

## What?
Include useForm and hedvig-ui components instead of Formik and material-ui

## Why?
For more coating of internal ui library

## Optional checklist
- [ ] Updated `src/components/payouts/payout-details/index.tsx`
- [ ] Codescouted
- [ ] Tested locally

2021-09-03 07:41 UTC, rasmusguterstam requested changes
This is so clean, really good job!! 🔥 Everything turns out so much better without material-ui and Formik 😄

The only thing I'm missing is a couple pictures and, even better, a short video of how the form looks and feels. If there's a lot of changes, I usually even go for a "Before" and "After" part, but that's up to you! 🙂

Also, I merged a bunch of stuff yesterday, so I believe you have some merge conflicts to sort out hehe

2021-09-03 07:41 UTC, rasmusguterstam commented on src/components/payouts/payout-details/index.tsx
> +      setConfirmed((currentConfirmed) => !currentConfirmed)
Really nice, the proper way of updating states 🤝

2021-09-03 07:41 UTC, rasmusguterstam commented on src/components/payouts/payout-details/index.tsx
> +    )
Just to make a callback to what I said during standup: this is a typical mutation where we _don't_ want to make an optimistic response, since it might very well fail! 🙂

2021-09-03 09:37 UTC, vonElfvin reviewed
Super neat! I have one little thing that I think is worth addressing that makes the code a bit simpler and the UX align with the rest

2021-09-03 09:37 UTC, vonElfvin commented on src/components/payouts/payout-details/index.tsx
> +    }
The latest "UX" is to use a `window.confirm` and not the double click functionality:
```suggestion
    if (!window.confirm(`Are you sure you want to payout ${data.amount} ${data.currency}?`)) {
      return
    }
```

2021-09-03 09:37 UTC, vonElfvin commented on src/components/payouts/payout-details/index.tsx
> +        )}
With using `window.confirm` above
```suggestion
  <SubmitButton variation="primary">Create payout</SubmitButton>
```

2021-09-03 09:37 UTC, vonElfvin commented on src/components/payouts/payout-details/index.tsx
>    const [confirmed, setConfirmed] = useState(false)
We can get rid of this one with `window.confirm` as well :)

2021-09-06 09:54 UTC, maxplt commented
Here is before/after screenshots of form
<img width="831" alt="Снимок экрана 2021-09-06 в 14 52 19" src="https://user-images.githubusercontent.com/89198006/132198491-fde87f5f-3829-4952-81f6-ecfd8b5fd5e0.png">
<img width="839" alt="Снимок экрана 2021-09-06 в 14 52 11" src="https://user-images.githubusercontent.com/89198006/132198507-82615396-36e2-4973-acc4-7696df1235f7.png">

2021-09-06 12:42 UTC, rasmusguterstam approved these changes

2021-09-06 12:46 UTC, merged