Feature/questions navigation
HedvigInsurance/hedgehog pull request #393
Opened 2021-09-15 11:58 UTC by maxplt

# Jira Issue: [IP-47](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-47)

## What?
Add ability to move between questions and interactions with hotkeys

## Why?
For better and fast interactions with Questions 

## Using video
https://user-images.githubusercontent.com/89198006/133428742-3d60265d-a1ea-481b-b5c1-0ae78373445c.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-09-15 12:00 UTC, rasmusguterstam commented on shared/@hedvig-ui/Form/form.tsx
> +  isFocus?: boolean
```suggestion
  focus?: boolean
```

2021-09-15 12:14 UTC, rasmusguterstam requested changes

2021-09-15 12:14 UTC, rasmusguterstam commented on shared/@hedvig-ui/Form/form.tsx
> +
Yeah that's a good point, but I'm thinking that it could be optional? So it's just normal if you're not specifying ref or something

2021-09-15 12:14 UTC, rasmusguterstam commented on src/features/questions/questions-list/AnswerForm.tsx
> +      )}
Nice!

2021-09-15 12:14 UTC, rasmusguterstam commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +
Instead of all this, you should probably look into the `useVerticalKeyboardNavigation` hook!

2021-09-16 07:17 UTC, maxplt commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +
@rasmusguterstam I’ve tried to use `useVerticalKeyboardNavigation` as you say
And it works not as well as needed. Will it be critical if remain as it is? With little refactor

2021-09-17 05:46 UTC, rasmusguterstam commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +  const [focusedInsideItem, setFocusedInsedItem] = useState(0)
```suggestion
  const [focusedInsideItem, setFocusedInsideItem] = useState(0)
```

2021-09-17 05:48 UTC, rasmusguterstam commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +
Of course you could have it this way if it works, but I don't really see why the hook wouldn't work. I believe it is has both a callback for `Escape`, `Up & Down` and `Enter`, which is like the nastiest part of the implementation? Perhaps we can take a look together today?

2021-09-20 12:43 UTC, vonElfvin reviewed
Very cool indeed! Super nice that you got this to work and with such a neat UX :) I added some thoughts.

Another thought that I couldn't find a suitable place for:
It looks like it's inputting a "newline character" when you focus the textarea in the form?

2021-09-20 12:43 UTC, vonElfvin commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +      setFocusedItem(length)
A bit confusing if it starts with 1 or what do you think?
```suggestion
      setFocusedItem(length - 1)
```

2021-09-20 12:43 UTC, vonElfvin commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +  const [focusedInsideItem, setFocusedInsideItem] = useState(0)
This could be a boolean maybe?

2021-09-20 12:43 UTC, vonElfvin commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +  const [focusedItem, setFocusedItem] = useState(1)
I personally like to use index to reason around things like these :)
```suggestion
  const [focusedItemIndex, setFocusedItemIndex] = useState(0)
```

2021-09-20 12:43 UTC, vonElfvin commented on shared/@hedvig-ui/Form/form.tsx
> +
Maybe we can keep the separate for now and see how this evolves

2021-09-20 12:43 UTC, vonElfvin commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +  const isOptionPressed = useKeyIsPressed(Keys.Option)
As I mentioned in slack and in IP-67 the "form submission hotkey" should be `Command + Enter` and not `Option + Enter` (sorry for the mixed signals 🙈 )
```suggestion
  const isCommandPressed = useKeyIsPressed(Keys.Option)
```

2021-09-21 04:07 UTC, maxplt commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +  const [focusedItem, setFocusedItem] = useState(1)
It will not working because of checking for a value. 0 is false and it brings some troubles

2021-09-21 04:07 UTC, maxplt commented on src/features/questions/questions-list/FilteredQuestionGroups.tsx
> +  const [focusedInsideItem, setFocusedInsideItem] = useState(0)
We need to check which item is focused

2021-09-21 13:14 UTC, rasmusguterstam commented on shared/@hedvig-ui/Form/form.tsx
> +    setFocus()
```suggestion
    setTimeout( () => {
      if (ref.current) {
        focus ? ref.current.focus() : ref.current.blur()
      }
    }, 1000)
```

2021-09-21 13:16 UTC, rasmusguterstam commented on src/features/questions/questions-list/QuestionGroupItem.tsx
> +    box-shadow: 0px 7px 8px 6px rgba(34, 60, 80, 0.2);
Extremely minor, but how does it look in dark mode? 😅

2021-09-21 13:17 UTC, rasmusguterstam approved these changes

2021-09-21 13:35 UTC, merged