Feature/claims filters
HedvigInsurance/hedgehog pull request #399
Opened 2021-09-20 05:41 UTC by maxplt

# Jira Issue: [IP-66](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-66)

## What?
Add Status and Age filter to claims list

## Why?
For convenient interaction and search of claims

## Video
https://user-images.githubusercontent.com/89198006/133960862-157eda6d-24d8-4da7-91eb-fa4a58c669e3.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-09-20 12:31 UTC, vonElfvin requested changes
Very neat solution I especially like how the filter communicates with the query 💯 

I think the UX for selected the state needs to be revisited, so we can select more granular queries 🙏

2021-09-20 12:31 UTC, vonElfvin commented on src/graphql/use-list-claims.tsx
> +          filterClaimStates: options?.filterClaimStates || [],
I think this one should be null if empty/not selected

2021-09-20 12:31 UTC, vonElfvin commented on src/pages/claims/list/ClaimsListPage.tsx
> +      filterClaimStates: [],
null (I think)
```suggestion
      filterClaimStates: null,
```

2021-09-20 12:31 UTC, vonElfvin commented on src/components/claims/filter/index.tsx
> +      />
I don't think a Dropdown is the correct selection tool for this scenario, for example I think showing `Opened` and `Reopened` will be a common use case. Either if we can get the dropdown to select `multi` (which I think should be available) or utilize checkboxes, similar to how we select Member groups/Countries in `Questions` tab.

2021-09-20 12:48 UTC, maxplt commented on src/components/claims/filter/index.tsx
> +      />
@vonElfvin As I know at the moment we can't filter with multiple values. And when it be able I guess we can use dropdown with multi select (as for me it look more clear) or like in Questions tab

2021-09-21 05:29 UTC, rasmusguterstam reviewed
Really nice! 😄 What do you say we add some labels to the fields as well so it's clear how what they filter on?

2021-09-21 05:40 UTC, maxplt commented
> Really nice! 😄 What do you say we add some labels to the fields as well so it's clear how what they filter on?

Agree! Will add them!

2021-09-21 07:36 UTC, maxplt commented
### Add labels
![image](https://user-images.githubusercontent.com/89198006/134130607-a63b9028-46f5-409e-b0ba-fc3437982963.png)

2021-09-21 11:31 UTC, rasmusguterstam commented
> ### Add labels
> ![image](https://user-images.githubusercontent.com/89198006/134130607-a63b9028-46f5-409e-b0ba-fc3437982963.png)

Can we make it so they're aligned to the left? This looks a bit weird 😅

2021-09-21 11:36 UTC, maxplt commented
> > ### Add labels
> > ![image](https://user-images.githubusercontent.com/89198006/134130607-a63b9028-46f5-409e-b0ba-fc3437982963.png)
> 
> Can we make it so they're aligned to the left? This looks a bit weird 😅

Done!

2021-09-21 13:10 UTC, rasmusguterstam approved these changes
Great job, just some conflicts to resolve! 😄 🚢

2021-09-21 13:33 UTC, fd-pliska commented on src/components/claims/filter/index.tsx
> +      />
They should be, but in the current state they are not - I made a mistake and passing more than one state breaks the query. It's going to be fixed in IP-49, though, so I suggest we wait to deploy filters to production until all three filters are ready. This is on me and I'm terribly sorry.

2021-09-22 09:09 UTC, vonElfvin commented on src/components/claims/filter/index.tsx
> +      />
No problems, let's assume they work and wait with merging this until they do :)

2021-10-04 13:29 UTC, maxplt commented
## Changes
I've maked a little changes to filters 🙂
Add multi select of filters with Checkboxes (Failed to implement an adequate dropdown multi-select)

https://user-images.githubusercontent.com/89198006/135859934-ba951cf8-fcda-440a-a5f1-6ced9514267d.mov

2021-10-08 15:21 UTC, vonElfvin reviewed
Very neat solution both code wise and design wise!

My only suggestion is maybe we can add some country flags, member group colors or maybe emojis like we have it in the Questions filters to make it a bit more 💅 

In addition to already existing stuff. Maybe add something like this to make it a bit more fun 🥳 :
🌊 Complex
📱 Simple

2021-10-11 13:38 UTC, merged