Feature/new tabs
HedvigInsurance/hedgehog pull request #414
Opened 2021-09-28 04:52 UTC by maxplt

# Jira Issue: [IP-79](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-79)

## What?
Create hedvig-ui equivalent for Tabs and implement it in Member page

## Why?
For better hotkey display 

## Video with new view
https://user-images.githubusercontent.com/89198006/135024903-61ceb8ac-2e84-42f4-8f96-7fb0689b5945.mov

## Previous view
![Снимок экрана 2021-09-28 в 09 37 53](https://user-images.githubusercontent.com/89198006/135024879-bbd4a999-7e19-4ba0-b739-230336e5e5dc.png)

## Problem
At the moment without new hotkeys view because I don't know how to implement them in better way.
If I will add it in their current form it will look like this (And it's not so good as I think):

![image](https://user-images.githubusercontent.com/89198006/135024919-8f6415a4-53fe-487a-9f34-c2ec7feec575.png)

### Wishes to improve the appearance of the tabs are welcome!

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-10-01 04:14 UTC, maxplt commented
### New view:
https://user-images.githubusercontent.com/89198006/135564165-f363e43b-7c32-42a2-af3a-70bf0d0dd355.mov

2021-10-01 06:17 UTC, rasmusguterstam commented on shared/@hedvig-ui/Form/form.tsx
> +import { sleep } from '../../../src/utils/sleep'
Why would you do this? 🤔

2021-10-01 06:17 UTC, rasmusguterstam commented on shared/@hedvig-ui/JsonSchemaForm/json-schema-form.tsx
> +} from '../../../src/utils/text'
Oh perhaps your merge is just off with master? 😅

2021-10-01 06:19 UTC, rasmusguterstam commented on shared/@hedvig-ui/Tabs/index.tsx
> +import { HotkeyStyled } from '@hedvig-ui'
I know this isn't part of this PR, but we shouldn't suffix things with "Styled" in `@hedvig-ui` - you should assume its properly styled, and then you can style it manually for a specific case

2021-10-01 06:21 UTC, rasmusguterstam commented on shared/@hedvig-ui/index.ts
> +// export type TabsProps = _TabsProps
Yeah you should probably do this one as well! 😄

2021-10-01 06:22 UTC, rasmusguterstam commented on src/features/member/index.tsx
> +          }))}
Really nice and slim solution compare to how it was, well done!

2021-10-01 06:34 UTC, rasmusguterstam requested changes
I'm really excited to use this component, but I added some thoughts 🤓

2021-10-01 06:34 UTC, rasmusguterstam commented on shared/@hedvig-ui/Tabs/index.tsx
> +  const path = history.location.pathname.split('/')
I see what you're doing here, but I believe this is a very specific implementation. What if I want to use these tabs for just a small case where there's only like two or three tabs as a part of a larger feature? I don't think I'd want to change route just because of that, but instead just keep track of some internal state of what to show.

 I also noticed that you removed `/:tab?` from `router.tsx`, which I believe makes these "routes" sort of hidden for anyone new to the codebase.

With that said, this `Tabs` implementation is very very clean and I like it a lot, but let's make it even more reusable as a pure UI component and not any opinionated and hidden implementation 😄

2021-10-04 16:09 UTC, vonElfvin reviewed
Really nice design now! I added some (maybe slightly outdated) thoughts to consider :)

2021-10-06 05:49 UTC, rasmusguterstam commented on shared/@hedvig-ui/Table/table.tsx
> +import { useVerticalKeyboardNavigation } from '../../../src/utils/keyboard-actions'
Yeah I agree!

2021-10-06 11:18 UTC, merged