Feature: Improve top bar
HedvigInsurance/hedgehog pull request #472
Opened 2021-11-01 08:41 UTC by maxplt

# Jira Issue: []

## What?
Make some upgrades of top menu and settings.
Replace theme toggler and logout button from Vertical menu to new User menu and settings.

## Video

https://user-images.githubusercontent.com/89198006/139645091-a6690927-e0de-4201-b485-85cba79275e5.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-11-03 08:46 UTC, rasmusguterstam commented on src/features/navigation/topbar/SettingsList.tsx
> +            </Option>
I don't really know why, but I think it makes more sense to have this one as an explicit item in the topbar 🤔

2021-11-03 08:47 UTC, rasmusguterstam commented on src/features/navigation/topbar/SettingsList.tsx
> +const SettingsList: React.FC<SettingsProps> = ({ setShowUsers }) => {
I really don't think we should call this menu `Settings`, since it's just a menu (which in turn contains an item to Settings).

2021-11-03 08:48 UTC, rasmusguterstam commented on src/features/navigation/topbar/SettingsList.tsx
> +}
No `any` pls 😅

2021-11-03 08:58 UTC, rasmusguterstam requested changes
Had some thoughts, but please challenge these if you want! 😄

2021-11-03 08:58 UTC, rasmusguterstam commented on src/features/navigation/topbar/SettingsList.tsx
> +const SettingsList: React.FC<SettingsProps> = ({ setShowUsers }) => {
Also, I think we should add the "darkmode" switch as a menu item here instead of a button on the settings page!

2021-11-03 08:58 UTC, rasmusguterstam commented on src/features/navigation/topbar/TopBar.tsx
> +export const CircleButton = styled.div`
Why `export`? Why not define it locally where it's used instead (`SettingsList`)?

2021-11-03 08:58 UTC, rasmusguterstam commented on src/features/navigation/topbar/TopBar.tsx
> +  align-items: center;
❌ It's already a styled `Flex`, use the props instead

2021-11-03 08:58 UTC, rasmusguterstam commented on src/features/navigation/topbar/TopBar.tsx
> +        <SettingsList me={me} setShowUsers={setShowUsers} />
Not really a fan of drilling the prop `setShowUsers` here. As already mentioned, I think if we rearrange a bit and put the "Users online" as a `CircleButton` in the top navigation, we don't have to do things like these. The responsibility of the `SettingsList` should just be to show a menu and, if anything, just have a general callback function that says which item was clicked (e.g. `<SettingsList onClickItem={(item: string) => ... } />`)

2021-11-03 08:58 UTC, rasmusguterstam commented on src/pages/settings/ProfilePage.tsx
> +import styled from '@emotion/styled'
As mentioned, I think these changes can be rolled back for now and instead put the darkmode switch in the menu

2021-11-03 08:58 UTC, rasmusguterstam commented on src/pages/tools/ToolsPage.tsx
> +        <Row columns={3}>
Heheh nice ⭐

2021-11-03 12:03 UTC, maxplt commented on src/features/navigation/topbar/SettingsList.tsx
> +const SettingsList: React.FC<SettingsProps> = ({ setShowUsers }) => {
@rasmusguterstam 
At first it was there. But I have command to move it into settings. I think I'll move it back. Will decide later
![image](https://user-images.githubusercontent.com/89198006/140056278-e20eccae-500c-4193-a0ab-5de4033bd83a.png)

2021-11-03 12:12 UTC, maxplt commented on src/features/navigation/topbar/TopBar.tsx
> +export const CircleButton = styled.div`
For less duplicates. It used in both components

2021-11-09 09:31 UTC, rasmusguterstam approved these changes

2021-11-09 09:46 UTC, merged