Feature: Create first version of templated claims filters
HedvigInsurance/hedgehog pull request #476
Opened 2021-11-02 12:14 UTC by maxplt

# Jira Issue: [IP-146](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-146)

## What?
Add ability to determine what filters should be present when navigating to a claims list by templated filters on Dashboard

## Why?
For better using of filters

## Video

https://user-images.githubusercontent.com/89198006/139843690-b48b7f47-6746-476b-ba3d-d0ea64b8abfb.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-11-11 09:01 UTC, vonElfvin reviewed
Unsure if the count is correct with the current solution, I added a comment on how to address that though :)

2021-11-11 09:01 UTC, vonElfvin commented on src/pages/dashboard/FilteredMetric.tsx
> +    })
Here we need a way to specify that we want the last page

2021-11-17 09:18 UTC, rasmusguterstam requested changes
Really cool!

However, you should revisit the file-structure. You currently have components under the `/pages` directory, and it's not matching the route hierarchy. I'd suggest creating a new sub-feature located, for example, at `/features/claims/claim-templates` and structure it accordingly.

Have a look at the README for reference! 🙂

2021-11-17 09:18 UTC, rasmusguterstam commented on src/pages/routes.tsx
> +const DashboardPage = lazy(() => import('./dashboard/DashboardPage'))
Have a look at the README; everything under `/pages` should correspond to our routes. DashboardPage is located at `hope.hedvig.com/dashboard`, and so the `DashboardPage` should be at the top-level.

2021-11-17 09:18 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +    <FilterWrapper className="claims__filter-wrapper">
How come we use `className`? 😮

2021-11-17 09:18 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +      const params = new URLSearchParams(location.search)
Can't we get the params directly from the `location` or router or anything?

2021-11-19 14:01 UTC, rasmusguterstam approved these changes
🔥 

Maybe remove the "date" from the template, might be confusing if it doesn't have the latest?Also, fix the conflicts then go ahead and merge! 😄

2021-11-22 12:13 UTC, hunt-hedvig commented
@maxplt prior to our chat earlier:

- [ ] Remove `date field` from template setup
- [ ] Truncate the template name displayed in cards if too lengthy
- [ ] Placeholder template name: `Claim Template n+1` if user input nth

2021-11-22 12:42 UTC, hunt-hedvig commented
[figma frames](https://www.figma.com/file/tf03s3dT4qZDZpX5YXuhVf/H.OPE-Redesign?node-id=742%3A1101) for implementation on claim listing page. cc @maxplt 

<img width="719" alt="Screenshot 2021-11-22 at 13 40 06" src="https://user-images.githubusercontent.com/94362755/142863545-b46b7639-3eba-4ec7-877c-172cf14cc0b3.png">

2021-11-23 12:32 UTC, hunt-hedvig commented
@maxplt one more minor comment,
1. select a filter template
2. change the filter items below
3. the template selected@1. should be deselected

https://user-images.githubusercontent.com/94362755/143024195-011acb15-745f-4b4a-9d34-44df526ee98d.mov

2021-11-23 12:43 UTC, hunt-hedvig commented
@rasmusguterstam @maxplt 
Not sure if its pure front-end bug,
there is a problem with the `number of member groups` when setting up templates.

1. Setup a new template and select 2 for the groups
2. Setup another new template and select 3 for the groups
3. The group number of template created@1. will be overwritten.

The latest created template will override all the previous templates' `number of member groups`

2021-11-24 08:39 UTC, rasmusguterstam commented on shared/@hedvig-ui/Modal/index.tsx
> +
Nice, almost always expected behavior 😄 

Optional, but you could also just do

```suggestion
useKeyIsPressed(Keys.Escape, () => props.onClose())
```

on line 110

2021-11-24 08:40 UTC, rasmusguterstam commented on shared/@hedvig-ui/Modal/use-confirm-dialog.tsx
> +
Reconsider the naming; `Content` feels very much like a div, body, container, wrapper-sort of - not a heading

2021-11-24 08:41 UTC, rasmusguterstam commented on shared/@hedvig-ui/Modal/use-confirm-dialog.tsx
> +
Or in this case, perhaps just reconsider the `h3` tag, because `Content` do make sense in the way it is used

2021-11-24 08:42 UTC, rasmusguterstam commented on shared/@hedvig-ui/Modal/use-confirm-dialog.tsx
> +  font-size: 14px;
Perhaps `rem`?

2021-11-24 08:44 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +      title={name ? name : 'Set Claim Filters'}
```suggestion
      title={name ? name : 'Create claim filter}
```

2021-11-24 08:48 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +}
```suggestion
interface CreateFilterProps {
  onClose: () => void
  editFilter?: ClaimsFiltersTypeWithName
  onCreate: (id: number, filters: ClaimsFiltersTypeWithName) => void
  id: number
}
```

2021-11-24 08:50 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +  }, [isEnterPressed])
```suggestion
  const isEnterPressed = useKeyIsPressed(Keys.Enter, () => {
      createFilter(id, { ...filters, name })
      close()
  })

  const [name, setName] = useState<string>(
    (editFilter && editFilter.name) || '',
  )
  const [filters, setFilters] = useState<ClaimsFiltersType>(
    editFilter || {
      filterClaimStates: null,
      filterCreatedBeforeOrOnDate: null,
      filterComplexities: null,
      filterNumberOfMemberGroups: null,
      filterSelectedMemberGroups: null,
      filterMarkets: null,
      filterTypesOfContract: null,
    },
  )
```

2021-11-24 08:51 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +  editFilter?: ClaimsFiltersTypeWithName
I can't tell what this is by just reading the names, what's going on here? You might want to reconsider the naming and data structure here so it's clearer

2021-11-24 09:06 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +        [field]: filters[field] ? [...filters[field], state] : [state],
Why are we doing this check, `filters[field] ? ...` when we already check it on line 41? Or maybe I'm mixing things up

2021-11-24 09:10 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +export default CreateFilterForm
Use named exports instead

2021-11-24 09:13 UTC, rasmusguterstam commented on src/features/claims/claim-templates/FilteredMetric.tsx
> +}
```suggestion
interface FilteredMetricProps {
  id: number
  filter: ClaimsFiltersTypeWithName
  onRemove: (id: number) => void
  onCreate: (id: number, filter: ClaimsFiltersTypeWithName) => void
  onEdit: (id: number, filter: ClaimsFiltersTypeWithName) => void
}
```

2021-11-24 09:23 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimsTemplates.tsx
> +}
```suggestion
interface TemplateProps {
  filters: ClaimsFiltersTypeWithName
  onSelect: (id: number) => void
  id: number
  active: boolean // Why not invert it? 😅 
}
```

2021-11-24 09:25 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimsTemplates.tsx
> +const AddTemplate = styled.div`
`AddTemplate` - what? Maybe add some explanatory suffix 😄

2021-11-24 09:26 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimsTemplates.tsx
> +const Template: React.FC<TemplateProps> = ({
Maybe?

```suggestion
const TemplateCard: React.FC<TemplateProps> = ({
```

2021-11-24 09:27 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +            groupsNumber={filters?.filterNumberOfMemberGroups || undefined}
Bro 😅 

```suggestion
            groupsNumber={filters?.filterNumberOfMemberGroups}
```

2021-11-24 09:28 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +                false
```suggestion
                isFilterExist(ClaimComplexity[key], 'filterComplexities')
```

2021-11-24 09:29 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +        <div style={{ display: 'flex' }}>
```suggestion
        <Flex>
```

2021-11-24 09:29 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +            groupsNumber={filters?.filterNumberOfMemberGroups || undefined}
```suggestion
            groupsNumber={filters?.filterNumberOfMemberGroups}
```

2021-11-24 09:41 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +}
Why not a styled component like we always do? 😳

2021-11-24 09:42 UTC, maxplt commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +            groupsNumber={filters?.filterNumberOfMemberGroups || undefined}
Ouch

2021-11-24 09:42 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimsTemplates.tsx
> +import styled from '@emotion/styled'
I don't think this file should be under `claims-list` feature, name it properly and put it under the `claim-templates` instead

2021-11-24 09:43 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListFilters.tsx
> +          (numb) => numb !== 2,
```suggestion
        claims: settings[UserSettingKey.MemberGroupsFilter].claims.filter(
          (memberGroup) => memberGroup !== 2,
```

2021-11-24 09:43 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListFilters.tsx
> +    }
```suggestion
      setDate?.(dateString) // Or maybe it is setDate.?(dateString), don't remember 
```

2021-11-24 09:44 UTC, maxplt commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +            groupsNumber={filters?.filterNumberOfMemberGroups || undefined}
@rasmusguterstam 😥
![image](https://user-images.githubusercontent.com/89198006/143214145-d7351bc6-c271-479f-a34b-87e8c6f8f18a.png)

2021-11-24 09:45 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +  const changeNumberMemberGroupsHandler = (state: number, field: string) => {
`state` as a parameter name feels _very_ reserved in React, maybe name it to what it is instead? Like `numberOfMemberGroups`?

2021-11-24 09:45 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +                false
```suggestion
                isFilterExist(ClaimComplexity[key], 'filterComplexities')
```

2021-11-24 09:46 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +  >()
Use `null` instead if it's intentionally empty

2021-11-24 09:48 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +  }
I don't think we should pollute the `ClaimsListPage` with all this logic. Let's create a hook in `claim-template/hooks` which manages this state internally and makes it easy to use instead?

2021-11-24 09:50 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +          setDate={!templated ? setDate : undefined}
I'd say that when you explicitly have to use `undefined`, it's a hint that you probably should do it another way. There's almost always an alternative to this 😄 

By the way, `templated` is just a boolean - does it really need a state? Can't it be determined just by looking at the `templateFilters` variable or something?

2021-11-24 09:50 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +        filters={templated ? filters : undefined}
No explicit `undefined` ❌

2021-11-24 09:52 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +      )
How come we're not using `useInsecurePersistentState` for this?

2021-11-24 09:53 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +    }
Do an early return instead at the top

2021-11-24 09:55 UTC, rasmusguterstam commented on src/pages/DashboardPage.tsx
> +const AddMetric = styled.div`
```suggestion
const AddMetricCard = styled.div`
```

2021-11-24 09:55 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +// TODO: SWAP WITH CLAIM LIST TEMPLATE FILTERS
Lol what

2021-11-24 09:57 UTC, rasmusguterstam requested changes
This is really cool, but some things to look over. Mostly regarding naming, structure and simplifying the logic!

2021-11-24 10:06 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +            groupsNumber={filters?.filterNumberOfMemberGroups || undefined}
So we don't even need the `?` then? Go and see if you can update the implementation while you're at it then, codescouting 🎉 🌟

2021-11-24 10:07 UTC, rasmusguterstam commented on src/pages/DashboardPage.tsx
> +}
This one doesn't really make sense, why not just

```suggestion
export interface TemplateFilters {
  filters: ClaimsFiltersTypeWithName[]
}
```

2021-11-24 10:08 UTC, rasmusguterstam commented on src/pages/DashboardPage.tsx
> +  name?: string
Why `undefined`? If it's undefined, isn't it just a good 'ol `ClaimsFiltersType` then? 😄

2021-11-24 16:19 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  }
Hehe you should probably define a return interface for this hook if we're going with all of these 😅

2021-11-24 16:21 UTC, rasmusguterstam commented on src/pages/DashboardPage.tsx
> +
MUCH better! 🌟

2021-11-25 09:14 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +import { Checkbox, Flex, Label } from '@hedvig-ui'
Since this file only is used internally within the `claim-templates` feature, I'd say that you could create a `components` folder and put it there

2021-11-25 09:16 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +  setFilters: (newFilter: ClaimsFiltersType, id?: number) => void
What's the point of `id?: number` here? We're not using it anywhere in this file? 🤔

2021-11-25 09:19 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +`
Nice!

2021-11-25 09:29 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +export default CreateFilterForm
@maxplt Haha don't resolve the conversation if you haven't fixed it 🤪

2021-11-25 09:29 UTC, rasmusguterstam commented on src/features/claims/claim-templates/FilteredMetric.tsx
> +export default FilteredMetric
❌

2021-11-25 09:32 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterForm.tsx
> +export const CreateFilterForm: React.FC<CreateFilterProps> = ({
```suggestion
export const CreateFilterModal: React.FC<CreateFilterProps> = ({
```

2021-11-25 09:34 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +}
Just a thought, but why not add `id` here as well? Every time we're passing `filter: ClaimsFiltersTypeWithName`, we also pass along an id, so why not combine them?

2021-11-25 09:36 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +}
Also, I think we should rename this interface to something like `ClaimFilterTemplate`, because it's being used as _the_ way to represent a template, right?

2021-11-25 09:37 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  const [selectedTemplate, setSelectedTemplate] = useState<number>()
Is the default supposed to be undefined/null? Because then I think we should be explicit with this

```suggestion
  const [selectedTemplate, setSelectedTemplate] = useState<number | null>(null)
```

2021-11-25 09:42 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  const filterQuery = useQuery().get('filter')
Not sure that the responsibility of grabbing the route param should be here, I think it would be better if it's an input to `useTemplateClaims` and is handled by the page instead

2021-11-25 09:44 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +interface Templates {
Too generic naming, go for something like `UseTemplateClaimsResult` instead

2021-11-25 09:45 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +}
If we rename the `ClaimsFiltersTypeWithName`, I think this interface is pretty redundant. If we only have one field, why not use it directly? 😄

2021-11-25 09:46 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +}
```suggestion
interface ClaimsTemplatesProps {
  activeId?: number
  templates: TemplateFilters
  onSelect: (id: number) => void
  onCreate: (id: number, filter: ClaimsFiltersTypeWithName) => void
}
```

2021-11-25 09:47 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +}
See my other comment on combining the `id` with `ClaimsFiltersTypeWithName` (and perhaps rename it). I think it's better if we're clear about what the `id` is about

```suggestion
interface TemplateCardProps {
  filter: ClaimsFiltersTypeWithName
  onSelect: (id: number) => void
  templateId: number
  active: boolean
}
```

2021-11-25 09:50 UTC, rasmusguterstam requested changes
Much better, but still some things to consider! 😄

2021-11-25 12:39 UTC, maxplt commented on src/features/claims/claim-templates/ClaimTemplateFilters.tsx
> +  setFilters: (newFilter: ClaimsFiltersType, id?: number) => void
Just old one

2021-11-26 08:57 UTC, rasmusguterstam reviewed
Hehe maybe we should enforce a name now that we have UUID:s instead of numbers? 😅 

![image](https://user-images.githubusercontent.com/51323202/143554204-ddbfbf28-b77f-4a21-9f08-7750c1583e3a.png)

2021-11-26 08:59 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +interface TemplateProps {
```suggestion
interface TemplateCardProps {
```

2021-11-26 09:00 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +  select: (id: string) => void
```suggestion
  onSelect: (id: string) => void
```

2021-11-26 09:01 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +  filter: ClaimFilterTemplate
To avoid confusion, we maybe should go with this naming instead?

```suggestion
  template: ClaimFilterTemplate
```

2021-11-26 09:02 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +  editableFilter?: ClaimFilterTemplate
```suggestion
  editableTemplate?: ClaimFilterTemplate
```

2021-11-26 09:03 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +  return (
Really like this entire file, it's very clean and concise 🌟 🌟

2021-11-26 09:03 UTC, rasmusguterstam commented on src/features/claims/claim-templates/FilteredMetric.tsx
> +  filter: ClaimFilterTemplate
```suggestion
  template: ClaimFilterTemplate
```

2021-11-26 09:07 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  const editTemplate = (newFilter: ClaimsFiltersType, id?: string) => {
Can't we do this now that we have the id in the template?

```suggestion
  const editTemplate = (newTemplate: ClaimsFiltersType) => {
```

2021-11-26 09:07 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  const createTemplate = (filter: ClaimFilterTemplate) => {
```suggestion
  const createTemplate = (template: ClaimFilterTemplate) => {
```

2021-11-26 09:07 UTC, rasmusguterstam commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  const selectTemplate = (id: string) => {
```suggestion
  const selectTemplate = (templateId: string) => {
```

2021-11-26 09:09 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListFilters.tsx
>    UserSettingKey,
You're getting the hang of it, really nice with a `/filters`!! 😄

2021-11-26 09:10 UTC, rasmusguterstam commented on src/features/claims/claims-list/filters/ClaimListTemplateFilters.tsx
> +  filters: ClaimsFiltersType
It makes sense to call this one `filters`, but as I've commented I think it makes sense to name `ClaimFilterTemplate` as `template` instead

2021-11-26 09:13 UTC, rasmusguterstam commented on src/features/questions/number-member-groups-radio-buttons.tsx
> +}) => {
I'm not sure what I think of introducing all these explicitly, could we keep this logic in a callback instead?

2021-11-26 09:14 UTC, rasmusguterstam commented on src/features/questions/number-member-groups-radio-buttons.tsx
> +}) => {
Maybe just have a `onToggle` and put the logic somewhere else?

2021-11-26 09:15 UTC, rasmusguterstam commented on src/pages/DashboardPage.tsx
> +                key={index + templateFilters.length}
Can't we do this now?

```suggestion
                key={filter.id}
```

2021-11-26 09:22 UTC, rasmusguterstam requested changes
Ok this is def the final feedback, I have to say that this looks really good now. Address my comments by fixing or commenting on why not, and then we'll finally go - I promise 🙌 🙌 🌟

2021-11-26 09:49 UTC, maxplt commented on src/features/claims/claim-templates/hooks/use-template-claims.ts
> +  const editTemplate = (newFilter: ClaimsFiltersType, id?: string) => {
@rasmusguterstam
It conflicts with localFilter because this one hasn't got id. 
Local filters needs for editing in Claims List view (on editing it makes request claims with current filters, so we don't need name and id in it).
And we need id while editing templates in Dashboard

2021-11-26 10:24 UTC, maxplt commented on src/features/questions/number-member-groups-radio-buttons.tsx
> +}) => {
I'm not sure how to realize that. Because in some situations we need to do `setNumberMemberGroups`, in some other ways we don't. (same with `updateSetting`)
So, besides `value` and `onToggle` it must be field something like `enableGlobalChange` (that blocks `setNumberMemberGroups`)
And I think it will be little more 'dirty'
What do you think, @rasmusguterstam ?

2021-11-26 10:29 UTC, rasmusguterstam commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +                : false
what

2021-11-26 10:31 UTC, rasmusguterstam commented on src/features/claims/claim-templates/FilteredMetric.tsx
> +    history.push(`/claims/list/1?filter=${template.id}`)
```suggestion
    history.push(`/claims/list/1?template=${template.id}`)
```

2021-11-26 10:31 UTC, maxplt commented on src/features/claims/claim-templates/ClaimsTemplatesList.tsx
> +                : false
Yeah😅
This place is little tricky one
Because we don't highlighting active template but changing nonactive 
And so when it's only one template and it's active we can't see changes

2021-11-26 10:33 UTC, rasmusguterstam approved these changes
👑 👑 👑

2021-11-26 10:46 UTC, merged