Feature: Add Popover to Claims Filters
HedvigInsurance/hedgehog pull request #478
Opened 2021-11-03 04:44 UTC by maxplt

# Jira Issue: [IP-137](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-137)

## What?
Add Popover to Claims Filters with additional info

## Why?
To clarify what the filters about

## Video

https://user-images.githubusercontent.com/89198006/140010939-35e11f8a-33be-4ae7-9811-aa393fe95db9.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-11-03 08:30 UTC, rasmusguterstam commented on shared/@hedvig-ui/Popover/popover.tsx
> +      <Contents style={style}>
If we extend `PopoverProps` with `React.HTMLAttributes<HTMLDivElement>` I think we should spread the remaining props on `Contents` as well. If not, it will appear as if all `div` props are allowed but they won't work. Better to have a component that behaves as expected 😄

2021-11-03 08:31 UTC, rasmusguterstam commented on shared/@hedvig-ui/Popover/popover.tsx
>    children,
```suggestion
  children,
  ...props
```

Something like this and just spread it to `Contents` instead of explicitly specifying `style`

2021-11-03 08:34 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +const LabelWithPropower = ({ label, propover }) => (
Typo 😅 

```suggestion
const LabelWithPopover = ({ label, popover }) => (
```

Also, it always makes me uncomfortable with untyped arguments - can we add that they're strings hehe? 😄

2021-11-03 08:35 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +  </StyledLabel>
What if we make the entire label + icon show the Popover? Instead of having to aim with your mouse exactly on the icon, you can just hover on whatever. 

Also,

```suggestion
  <StyledLabel>
    <span>{label}</span>
    <Popover style={{ width: 250 }} contents={popover}>
      <InfoCircle />
    </Popover>
  </StyledLabel>
```

2021-11-03 08:36 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +        />
```suggestion
        <LabelWithPopover
          label="Complexities"
          popover="A complex claim either has a reserve over 50k or is of type Water, Fire, Liability, Legal Protection or Flooding."
        />
```

2021-11-03 08:36 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +        />
```suggestion
        <LabelWithPopover
          label="Date up until"
          popover="The claim was registered either before or on this date."
        />
```

2021-11-03 08:36 UTC, rasmusguterstam requested changes
Nice! Some comments and thoughts

2021-11-03 10:07 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +  </StyledLabel>
@maxplt What do you think about this?

2021-11-03 11:53 UTC, maxplt commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +  </StyledLabel>
@rasmusguterstam I tried, but I think it looks not so good. Don't know 🤷‍♂️
![image](https://user-images.githubusercontent.com/89198006/140055292-7bdce7cd-5737-4bbb-a1e3-f0634fd45961.png)

2021-11-04 08:04 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +  </StyledLabel>
Alright skip it then 😄

2021-11-08 09:10 UTC, rasmusguterstam approved these changes

2021-11-08 15:54 UTC, merged