Feature/filters to settings
HedvigInsurance/hedgehog pull request #493
Opened 2021-11-09 04:58 UTC by maxplt

# Jira Issue: [IP-153](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-153)

## What?
Move filters of Claims and Questions from localStorage to User Settings.

## Why?
For more User Settings coverage

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-11-09 05:06 UTC, maxplt commented on src/features/conversations/overview/ConversationsOverview.tsx
> +        ...settings[UserSettingKey.FeatureFlags],
Don't like this action in every settings updating (if don't doing that, other fields will be cleared )
So, maybe we need to improve backend? Like when we send field in backend we will doing smth like 
`value: { ...settings[key], [key]: value }`

2021-11-09 08:57 UTC, rasmusguterstam commented on src/features/conversations/overview/ConversationsOverview.tsx
> +        ...settings[UserSettingKey.FeatureFlags],
This is on purpose, and it's a trade-off of how we model the settings in the backend. Everything within the same key, in this case `UserSettingKey.FeatureFlags`, will be reset so yes, we have to do like this. 

However, I think I should clarify that you should **not** use the same key for everything. For example, this is not how you should do it

```typescript
  const [selectedFilters, setSelectedFilters] = useState(
    settings[UserSettingKey.FeatureFlags]?.questions_filters || [
      FilterState.HasOpenClaim,
      FilterState.NoOpenClaim,
    ],
  )
```

Instead, use on of these 

![image](https://user-images.githubusercontent.com/51323202/140893468-8e1dd69b-d333-40b9-81d5-aad3b70b177d.png)

If you do, it won't override everything as soon as you update (unless there's a bug 😅 )

2021-11-09 09:00 UTC, rasmusguterstam requested changes
Have a look at the comments!

2021-11-09 09:00 UTC, rasmusguterstam commented on src/pages/QuestionsPage.tsx
> +  )
Use a different `UserSettingKey`

2021-11-09 09:00 UTC, rasmusguterstam commented on src/pages/QuestionsPage.tsx
> +    }
Reconsider the keys

2021-11-09 09:00 UTC, rasmusguterstam commented on src/pages/QuestionsPage.tsx
> +        Hey there <Capitalized>{getNameFromEmail(me.email)}</Capitalized>
```suggestion
        Hey there <Capitalized>{me.fullName}</Capitalized>
```

Or just extract the first name from the `fullName` as yesterday 😄

2021-11-09 09:00 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +    if (!settings[UserSettingKey.FeatureFlags]?.claims_filters) {
Same here

2021-11-09 09:00 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +    settings[UserSettingKey.FeatureFlags]?.claims_filters || EMPTY_FILTERS,
Same here

2021-11-09 09:00 UTC, rasmusguterstam commented on src/pages/claims/list/ClaimsListPage.tsx
> +    if (settings[UserSettingKey.FeatureFlags]?.claims_filters) {
You get the drill 🤓

2021-11-10 08:25 UTC, rasmusguterstam commented on src/features/conversations/overview/ConversationsOverview.tsx
>                      conversations: false,
Yeah I see the issue here. Would it make sense to extend `updateSetting` with an option such as `replace` which defaults to false? So it always spreads the previous values unless you explicitly say otherwise?

2021-11-10 08:27 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +                  'ClaimComplexityFilter',
```suggestion
                  'UserSettingKey.ClaimComplexityFilter',
```

2021-11-10 08:28 UTC, maxplt commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +                  'ClaimComplexityFilter',
Nope. In `updateFilterHandler` we need `key`, not `value`

2021-11-10 08:33 UTC, maxplt commented on src/features/conversations/overview/ConversationsOverview.tsx
>                      conversations: false,
I'm not sure how to realize it.

2021-11-10 08:39 UTC, rasmusguterstam requested changes
Have a look at the `UserSettingKey` again and make sure you use the proper keys. Also, remember that the values under a key can be _anything_, so you don't have to overengineer with a `claims: []` under a `UserSettingKey`.

Finally, I agree that it makes sense to create some helpers considering how unopinionated this settings model is. However, I also think this is a perfect opportunity to create some neat hooks, perhaps under `src/features/claims/hooks/*` and `src/features/questions/hooks`?

2021-11-10 08:39 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +                updateFilterHandler('MarketFilter', Market[key])
Don't use string value, be explicit

2021-11-10 08:39 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +  const updateFilterHandler = (field, value) => {
Specify types, specifically `field` should be `UserSettingKey` I assume?

2021-11-10 08:39 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +    })
Why do we need this `.claims`? Why can't we just store it directly? I mean we already have the UserSettingKey, so we know what to expect

2021-11-10 08:39 UTC, rasmusguterstam commented on src/features/questions/number-member-groups-radio-buttons.tsx
> +          updateSetting(UserSettingKey.NumberOfMemberGroups, { value: e })
Why not just 
```suggestion
          updateSetting(UserSettingKey.NumberOfMemberGroups, e)
```

2021-11-10 08:39 UTC, rasmusguterstam commented on src/pages/QuestionsPage.tsx
> +    settingField: UserSettingKey | undefined,
```suggestion
    settingField?: UserSettingKey,
```

2021-11-10 08:39 UTC, rasmusguterstam commented on src/pages/conversations/ConversationsOnboardingPage.tsx
> +  }, [selectedFilters])
Again, why the `UserSettingKey.FeatureFlags` when it has nothing to do with feature flags?

2021-11-10 08:39 UTC, rasmusguterstam commented on src/pages/conversations/ConversationsPage.tsx
>    )
Why do we even need a state? We already have the value?

2021-11-10 08:39 UTC, rasmusguterstam commented on src/pages/conversations/ConversationsSettingsPage.tsx
> +  )
Skip the state 😅

2021-11-10 08:47 UTC, maxplt commented on src/pages/conversations/ConversationsOnboardingPage.tsx
> +  }, [selectedFilters])
Forget to remove

2021-11-10 08:50 UTC, rasmusguterstam commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +                  'ClaimComplexityFilter',
Can we type this in some way then? `keyof UserSettingKey` or something like that? Feels dangerous to have strings that can be whatever when we actually know what to expect 🤓

2021-11-10 08:51 UTC, rasmusguterstam commented on src/features/conversations/overview/ConversationsOverview.tsx
>                      conversations: false,
Good point! Perhaps `replace` defaults to `true`, and when you deal with arrays or objects you can spread them **if** `replace` is expicitly set to `false`? Something like that, what do you think?

2021-11-10 11:02 UTC, maxplt commented on src/features/claims/claims-list/ClaimListFilters.tsx
> +                  'ClaimComplexityFilter',
Sorry, I'm the stupid one there. I don't know why, but I was getting values like `settings[UserSettingKey[key]]` instead of `settings[value]` 😰 😰 😰

2021-11-10 11:06 UTC, maxplt commented on src/features/questions/number-member-groups-radio-buttons.tsx
> +          updateSetting(UserSettingKey.NumberOfMemberGroups, { value: e })
In `updateSetting` second argument must be `object`. Not `string` or `number`

2021-11-10 11:25 UTC, maxplt commented on src/pages/conversations/ConversationsPage.tsx
>    )
Without state `useEffect` with `filters` dependecy constantly triggered 🤔

2021-11-11 11:40 UTC, rasmusguterstam commented on src/features/conversations/overview/ConversationsOverview.tsx
>                      conversations: false,
@maxplt

2021-11-17 09:06 UTC, rasmusguterstam approved these changes
🌟🌟🌟

Fix the conflicts then go ahead and merge! 😄

2021-11-19 12:57 UTC, merged