Feature: Keyboard navigation in Member Page
HedvigInsurance/hedgehog pull request #526
Opened 2021-12-03 05:02 UTC by maxplt

# Jira Issue: [IP-198](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-198)

## What?
Continue to making keyboard navigation. 
At the moment create some navigation stuff inside Member Page:
* Tabs
* Contracts
* Claims Table
* Files
* Quotes (sub tabs)
* Some navigation in Payments

## Why?
For 100% coverage of keyboard navigation

## Video
https://user-images.githubusercontent.com/89198006/144547845-d49e49c6-d43d-489d-a672-6906039bc409.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-12-03 10:14 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
>    }: ButtonProps & ButtonHTMLAttributes<HTMLButtonElement>) => {
If you extend in the props, you should remove this one!
```suggestion
  }: ButtonProps) => {
```

2021-12-03 10:15 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
> +    }, [focus])
```suggestion
        btnRef.current.focus()
        return
      }

      btnRef.current.blur()
    }, [focus])
```

2021-12-03 10:16 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
> +    }, [focus])
So why didn't we go with a hook here?
Where you could do something like

`useFocus(btnRef, focus)` and it does this nasty `useEffect` behind the scenes?

2021-12-03 10:17 UTC, rasmusguterstam commented on shared/@hedvig-ui/Modal/use-confirm-dialog.tsx
> +  }, [])
`useFocus`

2021-12-03 10:18 UTC, rasmusguterstam commented on shared/@hedvig-ui/Table/table.tsx
> +      })
Woah!

2021-12-03 10:19 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +  }, [])
`useFocus`?

2021-12-03 10:20 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +          setFocus={(value: string) => setFocus(value)}
Should be implied
```suggestion
          setFocus={(value) => setFocus(value)}
```

2021-12-03 10:21 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +        >
The `focus` should work now right?

2021-12-03 11:30 UTC, maxplt commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +  }, [])
Can't use `useFocus` here.
Because here we need to `setFocus` once and we are changing `focus` inside `Modal`
But `useFocus` tracking `focus` change and on every changing it'll be make `focus` as `Modal` (But we need for example `Modal filters focus` and etc.)

2021-12-03 11:36 UTC, maxplt commented on shared/@hedvig-ui/Modal/use-confirm-dialog.tsx
> +  }, [])
I've described the problem in other comment about `Modal`
In `useFocus` we're setting `focus` when it's `null` (it happens when user press `Escape` or in some another ways)
But here we need to `setFocus` whatever it is!

2021-12-03 12:00 UTC, maxplt commented on shared/@hedvig-ui/Button/button.tsx
>    }: ButtonProps & ButtonHTMLAttributes<HTMLButtonElement>) => {
Removing of it brings strange error 
![image](https://user-images.githubusercontent.com/89198006/144599164-f968f597-4c51-44a4-b69c-8ee8e0e6c39f.png)

2021-12-06 09:06 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
>    }: ButtonProps & ButtonHTMLAttributes<HTMLButtonElement>) => {
That's because you're extending with `React.HTMLAttributes<HTMLButtonElement>` on `ButtonProps` - use the same one you specified here, `extends ButtonHTMLAttributes<HTMLButtonElement>

2021-12-06 09:52 UTC, rasmusguterstam reviewed
I'm not a really a fan of the shadow as an indication of selection, nor the red color haha. But I like the slightly thicker border of the red one, but just perhaps change the color to a "focus blue" instead?

Also, some other thoughts (maybe have a chat with Hunt on these?):
- The scroll doesn't follow here, is it possible to use the same approach as with the claims list to make it follow?
- My first intuition here was to use the down-key to navigate downwards, not repeatedly press the right key
- In the quotes tab, how do a user now that they can press Shift + T? And how should we educate them?

Also, filters in claims doesn't work right now (you can navigate, but nothing happens on Enter)

![image](https://user-images.githubusercontent.com/51323202/144823562-1178dd69-3619-4f1d-a78f-b3da8eb12d5b.png)

2021-12-06 10:00 UTC, rasmusguterstam commented on shared/@hedvig-ui/Input/input.tsx
> +    useElementFocus(inputRef, focus || false)
Nice!

2021-12-06 10:04 UTC, rasmusguterstam commented on shared/@hedvig-ui/Tabs/index.tsx
>    }, [navigationAvailable])
`useElementFocus`? 🤓

2021-12-06 10:04 UTC, rasmusguterstam commented on shared/@hedvig-ui/Tabs/index.tsx
>    }, [navigationAvailable])
Or maybe that's not what's going on here

2021-12-06 10:15 UTC, rasmusguterstam commented on src/features/claims/claim-templates/CreateFilterModal.tsx
> +          setFocus={(value: string) => setFocus(value)}
@maxplt why resolve without changing 😢

2021-12-06 10:29 UTC, rasmusguterstam reviewed
Another thing that struck me is that you will have to document how this "framework" is supposed to be used in the future. If I or any other developer were to add a new card in any view, what are the steps required to be compliant with the keyboard navigation? How can we produce a working example, step by step? If there's too much hassle, this feature will most likely fade away 😕

Use the empty design document [here](https://www.notion.so/hedviginsurance/Internal-Product-Roadmap-9ffd801fb7a649d0b83df1f86fd361ea?p=11a3fa6590214e3584b3a4f0830ceb25), and for inspo you can have a look at [Resource Access Design Document](https://www.notion.so/hedviginsurance/Design-Document-Resource-Access-b3b783e64a374e51a12dfe0b29044a89) and [all of these](https://www.notion.so/hedviginsurance/Software-Design-Documents-21fac504db224a02a19c539e759a20e2).

2021-12-06 10:35 UTC, rasmusguterstam commented on src/features/claims/claims-list/FilterElements.tsx
> +    },
```suggestion
    onNavigationStep: () => onNavigationStep?.(navigationStep)
    },
```

2021-12-06 10:36 UTC, rasmusguterstam commented on src/features/member/tabs/account-tab/MonthlyEntriesTable.tsx
> +        }}
What's going on here

2021-12-06 10:42 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/agreement/AgreementsTable.tsx
> +    >
Naah 😕

2021-12-06 10:43 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/agreement/AgreementsTable.tsx
> +    >
See my general comment

2021-12-06 10:43 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/agreement/index.tsx
> +  const buttons = useElementsInsideParent(cardsRef, 'button')
Really cool!

2021-12-06 10:44 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/contract/index.tsx
> +  }, [focused])
Don't we have a hook for this now?

2021-12-06 11:10 UTC, maxplt commented on shared/@hedvig-ui/hooks/keyboard/use-arrow-keyboard-navigation.ts
> +
But we use it for active element in `VerticalMenu`. And it changes. Without `useEffect` it doesn't work

2021-12-06 11:19 UTC, maxplt commented on src/features/member/tabs/account-tab/MonthlyEntriesTable.tsx
> +        }}
`onPerformNavigation` is required in `useArrowKeyboardNavigation` for working. But here I don't need it. So it's empty function

2021-12-06 12:19 UTC, hunt-hedvig commented
`In the quotes tab, how do a user now that they can press Shift + T? And how should we educate them?`

Interesting catch, I find it not exactly intuitive as imagined on this one as well. Two scenarios come across in my head.
The lazy one:
just include the shift+T command in the CLI tool for the IEX team to find out the hotkey themselves

The revamped one:
on the other hand, instead of using shift+T, the default primary focus after entering the `quotes tab` will land on the sub-tab items, user will hv to choose one of the sub-tabs before entering the next layer(quote listing).

vote?
1️⃣ the lazy one
2️⃣ the revamped one

2021-12-08 08:35 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
>          <ButtonIconWrapper>
I commented this on your other PR hehe, but use forwardRef and use an internal ref if it's not defined

2021-12-08 08:35 UTC, rasmusguterstam commented on shared/@hedvig-ui/Card/card.tsx
> +  useElementFocus(cardRef, focus || false)
Same here

2021-12-08 08:36 UTC, rasmusguterstam commented on shared/@hedvig-ui/Table/table.tsx
>    }, [active])
Is this a place where `useElementFocus` can be used?

2021-12-08 08:37 UTC, rasmusguterstam commented on shared/@hedvig-ui/Tabs/index.tsx
> +  const tabsRef = useRef<HTMLUListElement>(null)
Same here

2021-12-08 08:38 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/keyboard/use-arrow-keyboard-navigation.ts
>        }
```suggestion
      if (withNegative ? navigationIndex === -1 : navigationIndex === 0) {
        onExit?.()
      }
```

2021-12-08 08:40 UTC, rasmusguterstam commented on src/features/member/tabs/account-tab/index.tsx
> +          }
Yeah you will have to reconsider this naming 😅

2021-12-08 08:42 UTC, rasmusguterstam commented on src/features/member/tabs/campaigns-tab/campaigns/CampaignsInfo.tsx
> +const CampaignCard = styled(Card)<{ focused: boolean }>`
And a `Card` also has a `focus?: boolean` prop, right? Maybe reconsider the naming here as well?

2021-12-08 08:48 UTC, rasmusguterstam commented on src/features/member/tabs/files-tab/FileTab.tsx
> +      memberFiles={data.member!.fileUploads}
```suggestion
      memberFiles={data.member.fileUploads}
```

2021-12-08 08:49 UTC, rasmusguterstam commented on src/features/member/tabs/member-tab/MemberTab.tsx
> +  const { focus } = useNavigation()
Redeclared, see line 86

2021-12-08 08:50 UTC, rasmusguterstam commented on src/features/member/tabs/member-tab/MemberTab.tsx
> +  useFocus(FocusItems.Member.items.Member)
Redeclared, see line 86

2021-12-08 08:53 UTC, rasmusguterstam commented on src/features/member/tabs/payments-tab/PaymentsTab.tsx
> +          focused={navigationStep + 1 === 0}
Reconsider naming

2021-12-08 08:54 UTC, rasmusguterstam commented on src/features/member/tabs/payments-tab/PayoutDetails.tsx
> +    // maxStep: cardsRef.current?.children.length || 0,
?

2021-12-08 09:01 UTC, rasmusguterstam requested changes
Some small things left to consider! 😄

2021-12-09 09:38 UTC, rasmusguterstam approved these changes
Alright I'd say this is _fine_ for now as it does the job, but with respect to maintainability I see some proper issues with props being spread and drilled all over the place. We will have to reconsider this down the road 🤔

2021-12-10 06:50 UTC, merged