Feature: Claim Page navigation
HedvigInsurance/hedgehog pull request #527
Opened 2021-12-07 05:34 UTC by maxplt

# Jira Issue: [IP-198](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-198)

## What?
In Claim Page add navigation by arrow keys:
* Between tabs in Member info
* Claim info elements
* Add navigation between cards (vertical + horizontal)

At the moment navigation in Payments card is working by `Tab`

## Why?
For more keyboard coverage 

## Video

https://user-images.githubusercontent.com/89198006/144972096-566368ed-6e3a-4a46-a266-340258de83ea.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-12-08 08:24 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
> +      <button {...props} ref={btnRef}>
What if I want to use a ref from outside the component? Take a look at [https://reactjs.org/docs/forwarding-refs.html](https://reactjs.org/docs/forwarding-refs.html) and do a mix or something, so that if it's not specified it will use an internal ref. I think this is implemented in a couple of other places, have a look around!

2021-12-08 08:25 UTC, rasmusguterstam commented on shared/@hedvig-ui/Checkbox/checkbox.tsx
> +
Same here

2021-12-08 08:26 UTC, rasmusguterstam commented on shared/@hedvig-ui/Dropdown/dropdown.tsx
>    }
```suggestion
  const closeDropdown = () => {
    onClose?.()
    setActive(false)
  }
```

2021-12-08 08:27 UTC, rasmusguterstam commented on shared/@hedvig-ui/SearchableDropdown/searchable-dropdown.tsx
> +  const selectRef = useRef<any>(null)
Change type?

2021-12-08 08:27 UTC, rasmusguterstam commented on shared/@hedvig-ui/SearchableDropdown/searchable-dropdown.tsx
> +  useElementFocus(selectRef, props.focus || false, false)
Nice use!

2021-12-08 08:30 UTC, rasmusguterstam commented on src/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +              onClose={() => setActive(false)}
Why do we do this?

2021-12-08 08:33 UTC, rasmusguterstam commented on src/pages/claims/ClaimDetailsPage.tsx
> +  }, [verticalStep])
This if fine for now, but hopefully my branch can address this a bit 🙏

2021-12-08 08:33 UTC, rasmusguterstam requested changes
Have a look at the forwarded refs, so the core components maintain expected behavior!

2021-12-08 10:57 UTC, maxplt commented on src/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +              onClose={() => setActive(false)}
@rasmusguterstam For move between `dropdowns` and other elements with arrow keys. Without it, if the `dropdown` opens, you will navigate between it and also inside `Card` if will use arrows.
So, on opening some dropdown active becomes true and `useArrowKeyboardNavigation` becomes disabled.

2021-12-09 08:47 UTC, rasmusguterstam commented on shared/@hedvig-ui/Button/button.tsx
> +        <button {...props} ref={ref ?? internalRef}>
Do something like this instead

```suggestion
  React.forwardRef(
    (
      { icon, children, focus, ...props }: ButtonProps,
      forwardRef: React.ForwardedRef<HTMLButtonElement>,
    ) => {
      const internalRef = useRef<HTMLButtonElement>(null)
      const ref = forwardRef ?? internalRef
      
      useElementFocus(
        ref,
        focus || false,
      )

      return (
        <button {...props} ref={ref}>
```

2021-12-09 08:47 UTC, rasmusguterstam commented on shared/@hedvig-ui/Card/card.tsx
> +      <CardContainer ref={ref ?? internalRef} {...cardProps}>
Same here

2021-12-09 08:48 UTC, rasmusguterstam commented on shared/@hedvig-ui/Checkbox/checkbox.tsx
> +      focus || false,
Same

2021-12-09 08:50 UTC, rasmusguterstam commented on shared/@hedvig-ui/Modal/index.tsx
> +  }, [])
We shouldn't do this at all here, this is a core @hedvig-ui component ❌

2021-12-09 08:51 UTC, rasmusguterstam commented on shared/@hedvig-ui/SearchableDropdown/searchable-dropdown.tsx
> +  )
This is more fine, as `useElementFocus` (c)(sh)ould be in @hedvig-ui/hooks, since it's generic

2021-12-09 08:52 UTC, rasmusguterstam commented on shared/@hedvig-ui/Tabs/index.tsx
> +    const internalRef = useRef<HTMLUListElement>(null)
Same as before

2021-12-09 09:15 UTC, rasmusguterstam commented on src/features/member/tabs/account-tab/AccountEntryTable.tsx
> +                      {entry.reference}
Haha has this never worked then..? 😳

2021-12-09 09:18 UTC, rasmusguterstam commented on src/features/member/tabs/campaigns-tab/campaigns/CampaignCodeInput.tsx
> +          }}
Can't we just wrap it in a form and use the onSubmit?

2021-12-09 09:18 UTC, rasmusguterstam commented on src/features/member/tabs/campaigns-tab/campaigns/CampaignCodeInput.tsx
> +          onClick={redeemHandler}
Hehe nice!

2021-12-09 09:19 UTC, rasmusguterstam commented on src/features/member/tabs/campaigns-tab/index.tsx
> +        navStep={navigationStep}
Preferably no shorthands
```suggestion
        navigationStep={navigationStep}
```

2021-12-13 18:06 UTC, rasmusguterstam commented
After looking very closely into both the previous PRs and this one, I'll put this one on draft as this most likely is not the way we want to go moving forward.

2021-12-17 05:48 UTC, closed without merging