Feature: Display self-change blockers
HedvigInsurance/hedgehog pull request #533
Opened 2021-12-13 12:34 UTC by maxplt

# Jira Issue: [IP-211](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-211)

## What?
Show self-change blockers on a member's contract tab if there exists

Not sure which values can be, so I've added colors for `termination` and `future changes` types. And `accent` color by **default**. 

## Screenshots
![Снимок экрана 2021-12-13 в 17 28 45](https://user-images.githubusercontent.com/89198006/145812501-1625c2a5-8132-4e8e-8a5c-2c354a18f2b7.png)
![Снимок экрана 2021-12-13 в 17 29 27](https://user-images.githubusercontent.com/89198006/145812509-c2a8e768-d09b-4fca-8919-75f9ea41552e.png)

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-12-13 17:58 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/contract/index.tsx
> +}
Use existing utils instead, something like `convertEnumToSentence`

2021-12-13 18:02 UTC, rasmusguterstam approved these changes
Really cool! Maybe have a sync with Hunt on the layout? I'm thinking that maybe it's not something that should always be top-level information for IEX, since self-change is just one feature 🤔 

I'll approve, but check with him first 😄

2021-12-15 05:27 UTC, maxplt commented
## New view

<img width="880" alt="Снимок экрана 2021-12-15 в 10 25 42" src="https://user-images.githubusercontent.com/89198006/146128569-1b03fc57-a423-49a2-b315-033f93b2fb2e.png">
<img width="872" alt="Снимок экрана 2021-12-15 в 10 25 52" src="https://user-images.githubusercontent.com/89198006/146128575-1ff13f64-c4a4-4459-9d57-ccff5e45ccca.png">

2021-12-15 15:24 UTC, rasmusguterstam commented
> ## New view
> <img alt="Снимок экрана 2021-12-15 в 10 25 42" width="880" src="https://user-images.githubusercontent.com/89198006/146128569-1b03fc57-a423-49a2-b315-033f93b2fb2e.png">
> 
> <img alt="Снимок экрана 2021-12-15 в 10 25 52" width="872" src="https://user-images.githubusercontent.com/89198006/146128575-1ff13f64-c4a4-4459-9d57-ccff5e45ccca.png">

Yeah this ain't it. The blockers are not the action in itself, they are the reasons as to why the user can't do self-change (which currently is to change address, this was called "Moving flow" before)

2021-12-15 15:25 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/contract/index.tsx
> +const blockersTranslates = {
```suggestion
const blockerDisplayName = {
```

2021-12-15 15:26 UTC, rasmusguterstam commented on src/features/member/tabs/contracts-tab/contract/index.tsx
> +  background-color: ${({ theme }) => theme.accentLighter ?? colorsV3.white};
What is this default behavior about?

2021-12-15 15:28 UTC, rasmusguterstam commented on shared/@hedvig-ui/OrbIndicator/orb-indicator.tsx
> +    <OrbIndicatorStyled color={currentColor} size={size || '10px'} {...props} />
Why not style it inline if you really need 10px in one place?

2021-12-15 15:29 UTC, rasmusguterstam requested changes
I think there's some misunderstanding as to what these blockers mean 😅

2021-12-16 04:58 UTC, maxplt commented on src/features/member/tabs/contracts-tab/contract/index.tsx
> +  background-color: ${({ theme }) => theme.accentLighter ?? colorsV3.white};
I just copied that kind of _background_ from `Card` _styles_ 🥲

2021-12-16 05:03 UTC, maxplt commented on shared/@hedvig-ui/OrbIndicator/orb-indicator.tsx
> +    <OrbIndicatorStyled color={currentColor} size={size || '10px'} {...props} />
Sorry, I didn't understand what you mean 😓
Do you mean to use a construction like this?
`<OrbIndicatorStyled style={{ height: size || '10px', width:  size || '10px' }} {...props} />`

2021-12-16 08:49 UTC, hunt-hedvig commented
Sorry for the hassle, I simply relocate the blocker to the bottom of each contract. let's see if this will fit ;)
@rasmusguterstam @maxplt 

![image](https://user-images.githubusercontent.com/94362755/146338384-8327c6bd-0a36-44ac-b9ee-f96b34009747.png)

2021-12-16 11:44 UTC, maxplt commented
## New view again!

![Снимок экрана 2021-12-16 в 16 40 03](https://user-images.githubusercontent.com/89198006/146365882-197ab3d2-c281-4163-a2da-0be30c09361b.png)

2021-12-17 05:56 UTC, rasmusguterstam commented on shared/@hedvig-ui/OrbIndicator/orb-indicator.tsx
> +    <OrbIndicatorStyled color={currentColor} size={size || '10px'} {...props} />
No I just mean why default to 10px, if you need 10px in once place then just use the inline style for it in that particular instance

2021-12-17 05:57 UTC, rasmusguterstam approved these changes
Nice, now we're on the same page 😄

2021-12-17 10:22 UTC, merged