Feature: Add outcome filter in claims
HedvigInsurance/hedgehog pull request #535
Opened 2021-12-15 06:41 UTC by maxplt

# Jira Issue: [IP-209](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-209)

## What?
Add ability to filter claims list by outcome
At the moment I didn't implement it in templates

## Why?
To be able to filter by outcome

## Video

https://user-images.githubusercontent.com/89198006/146136128-0f0c78f5-3fc4-4b88-bf58-3be64b8f58d4.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2021-12-15 08:15 UTC, vonElfvin commented
Nice! Could this be multi-select as well? So you can select more than one

2021-12-15 09:45 UTC, maxplt commented
## Add multi select ability

https://user-images.githubusercontent.com/89198006/146162686-a45ef8b3-2f3d-4666-a55d-f43edb3a77c9.mov

2021-12-17 05:59 UTC, rasmusguterstam commented on shared/@hedvig-ui/Dropdown/dropdown.tsx
> +  selectedValue?: string
Maybe just `value` instead? Feels more lite expected behavior?

2021-12-17 06:01 UTC, rasmusguterstam commented on shared/@hedvig-ui/Dropdown/dropdown.tsx
>    children: any
I know there's no diff here, but if we extend with `HTMLAttributes<HTMLDivElement>` we don't need this one

2021-12-17 06:03 UTC, rasmusguterstam commented on src/features/claims/claim-details/ClaimType/components/OutcomeDropdown.tsx
> +}) => {
I feel like we've been through this already, don't we have a multi-select dropdown already? 🤔

2021-12-17 06:05 UTC, rasmusguterstam commented on src/features/claims/claim-details/ClaimType/components/OutcomeDropdown.tsx
> +          : undefined
If this check is required, I think the implementation has to change. Perhaps time to add (if we don't have one already) a multi-dropdown to @hedvig-ui?

2021-12-17 06:05 UTC, rasmusguterstam commented on src/features/claims/claim-details/ClaimType/components/OutcomeDropdown.tsx
> +                (outcome === null && opt.value === 'not_specified' && false)
Same here, this is pretty intense. Would be cool if it could happen behind the scenes instead, since this is just for the styling right?

2021-12-17 06:10 UTC, rasmusguterstam requested changes
Cool! Some thoughts on the multi-dropdown

2021-12-20 13:01 UTC, maxplt commented
### Use exist multi-dropdown


https://user-images.githubusercontent.com/89198006/146771106-f0bbd005-109e-44e5-a2b8-c005d2a08a11.mov

2021-12-21 07:42 UTC, rasmusguterstam commented on shared/@hedvig-ui/Dropdown/dropdown.tsx
>    children: any
```suggestion
  children: React.ReactNode
```

2021-12-21 07:43 UTC, rasmusguterstam commented on shared/@hedvig-ui/Dropdown/multi-dropdown.tsx
> +  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
Nice!

2021-12-21 07:45 UTC, rasmusguterstam commented on shared/@hedvig-ui/Radio/radio.tsx
> +export const Radio: React.FC<RadioProps> = ({
If it's going to be optional, we maybe even could remove the `Omit` and just use the extended?

2021-12-21 07:47 UTC, rasmusguterstam approved these changes

2021-12-22 07:45 UTC, maxplt commented on shared/@hedvig-ui/Dropdown/dropdown.tsx
>    children: any
Doesn't work with it :(

![image](https://user-images.githubusercontent.com/89198006/147054873-1875030c-8815-4ab0-a5e4-f742eef01333.png)

2021-12-22 07:48 UTC, maxplt commented on shared/@hedvig-ui/Radio/radio.tsx
> +export const Radio: React.FC<RadioProps> = ({
We need event like `div` element in `onKeyDown` because we implement it in `div` element. But extended **props** are from `input` element

2021-12-22 12:39 UTC, rasmusguterstam commented on shared/@hedvig-ui/Radio/radio.tsx
> +export const Radio: React.FC<RadioProps> = ({
Ah alright!

2021-12-22 12:39 UTC, rasmusguterstam approved these changes
Just some stuff to resolve 😎

2021-12-23 05:20 UTC, merged