Feature: Template messages
HedvigInsurance/hedgehog pull request #561
Opened 2022-01-21 08:52 UTC by maxplt

# Jira Issue: []

## What?
Create Template Messages tool for Conversations
Add page in Tools where you can check/create/edit/delete template messages.
And add a section of templates on the Conversations page where you can use them and also create/edit/pin.
At the moment everything is stored on localStorage  

## Why?
For faster writing template answers

## Video

https://user-images.githubusercontent.com/89198006/150496245-0f2ac400-ca9c-452b-9fc8-eb35727e10fe.mov

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2022-01-24 09:15 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +const TextAreaBottom = styled.div`
Maybe something like `TextAreaFooter`?

2022-01-24 09:24 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/TemplateForm.tsx
> +              )[0].text || ''
Use `find` instead

2022-01-24 09:25 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/TemplateForm.tsx
> +              )[0].text || ''
`find`

2022-01-24 09:25 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/TemplateForm.tsx
> +              )[0].text || ''
You know it 😄

2022-01-24 09:26 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/TemplateMessages.tsx
> +  }
Nice!

2022-01-24 09:29 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +}
We already have a definition or these in `constants.ts`

2022-01-24 09:30 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +  market: Markets
Also, enums (and types) should usually go as singular so you can do `market: Market` instead 😄

2022-01-24 09:34 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +  changeCurrentMarket: (market: Markets) => void
Maybe have a more consistent naming here, something like

```suggestion
  templates: TemplateMessage[]
  show: () => void
  create: (template: TemplateMessage) => void
  edit: (template: TemplateMessage) => void
  delete: (id: string) => void
  pin: (id: string) => void
  select: (text: string) => void
  selected: string | null
  market: Market
  setMarket: (market: Market) => void
```

I'm thinking that the hook implies some sort of namespacing when you're using it? I guess you also could go the other way around, suffixing everything with *Template

2022-01-24 09:35 UTC, rasmusguterstam commented on src/portals/hope/pages/tools/TemplateMessagesPage.tsx
> +const TemplateMessagesPage = () => {
🤓 

```suggestion
const TemplateMessagesPage: Page = () => {
```

2022-01-24 09:37 UTC, rasmusguterstam reviewed
Looks really good! 🌟

2022-01-24 09:49 UTC, maxplt commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +}
@rasmusguterstam Are you sure that we can use it? This one is outside of `hedvig-ui`

2022-01-30 16:00 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +    )
Maybe simplify this a bit

2022-01-30 16:00 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +      .map((letter, idx) => {
```suggestion
      .map((letter, index) => {
```

2022-01-30 16:02 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +      !!proposedTemplate
```suggestion
      proposedTemplate
```

2022-01-30 16:02 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +        .map((tmpl) => tmpl.id)
```suggestion
      const templatesIds = templates
        .filter((template) => template.market.includes(market))
        .filter(
          (template) =>
            template.name.substring(0, searchText.length).toLowerCase() ===
            searchText.toLowerCase(),
        )
        .map((template) => template.id)
```

2022-01-30 16:03 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +            (tmpl) => tmpl.id === templatesIds[indexOfCurrentTemplate + 1],
Same here, try not to use abbreviations

2022-01-30 16:11 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/SearchTemplate.tsx
> +  const [query, setQuery] = useState<string>()
```suggestion
  const [query, setQuery] = useState('')
```

2022-01-30 16:12 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/SearchTemplate.tsx
> +    templates
```suggestion
  const getFilteredTemplates = 
    templates
```

2022-01-30 16:13 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/TemplateForm.tsx
> +  const [expiryDate, setExpiryDate] = useState(template?.expiryDate || null)
```suggestion
  const [expiryDate, setExpiryDate] = useState<Date | null>(template?.expiryDate || null)
```

2022-01-30 16:15 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/components/TemplateForm.tsx
> +          !!template.market.filter((market) => markets.includes(market)).length,
Can be simplified with the `some` function

2022-01-30 16:22 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +    toast.success('Template successfully pinned')
Maybe just this, since there's not really a risk it won't work 😅 

```suggestion
    toast.success('Template pinned')
```

2022-01-30 16:22 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +    toast.success('Template successfully edited')
```suggestion
    toast.success('Template successfully edited')
```
```suggestion
    toast.success('Template updated')
```

2022-01-30 16:23 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +    toast.success('Template successfully deleted')
```suggestion
    toast.success('Template deleted')
```

2022-01-30 16:24 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +}
Not sure it's a good idea to just export an interface called `Message`. Why isn't it called `TemplateMessage`? And why is the second called `TemplateMessage` when it contains several messages..?

2022-01-30 16:27 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +import React, { createContext, useContext, useState } from 'react'
Maybe we can move this entire folder (`template-messages`) up one step instead of having it under `tools`? So it's located at `src/portals/hope/features/template-messages` instead?

2022-01-30 16:35 UTC, rasmusguterstam commented on src/portals/hope/features/tools/template-messages/use-template-messages.tsx
> +    toast.success('Template successfully pinned')
Also, when I remove the pin it still toasts with "Template successfully pinned" 🤓

2022-01-30 16:40 UTC, rasmusguterstam reviewed
I absolutely love this feature, it's so clean and it works very well! 🌟 

I'm guessing we'll leave this PR open for now until we have the back-office implementation ready. Would be great if you and Vladimir could have a sync Monday morning on this to sync on the requirements.

2022-01-31 05:12 UTC, maxplt commented on src/portals/hope/features/tools/template-messages/components/TemplateForm.tsx
> +  const [expiryDate, setExpiryDate] = useState(template?.expiryDate || null)
@rasmusguterstam 
But `expiryDate` field is a string like '_2022-01-31_' 🧐

2022-01-31 05:33 UTC, maxplt commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +    )
Not sure how to simplify in that case 😰

2022-02-15 08:23 UTC, maxplt commented
Added lib `react-linkify` to find and implement links in the messages

Before:
![image](https://user-images.githubusercontent.com/89198006/154021594-08c20269-4c4a-4993-9f60-2d9896df2883.png)


After:
![image](https://user-images.githubusercontent.com/89198006/154021501-5a9cd962-84e2-42d6-a9a0-22a73e15564b.png)

2022-02-17 15:16 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/SearchTemplate.tsx
> +  }
```suggestion
  const selectHandler = (id: string) => {
    const selectedTemplate = templates.find(
      (template) => template.id === id,
    )
    onSelect(selectedTemplate)
  }
```

2022-02-17 15:23 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateForm.tsx
> +    })
Not sure I'm following what's going on here, especially not the `message-` prefix?

2022-02-17 15:24 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateForm.tsx
> +  const [markets, setMarkets] = useState<Language[]>([])
We should at least rename the variables to `languages` etc, since "market" and "language" are pretty different

2022-02-17 15:27 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateForm.tsx
> +        )}
We made an effort a while ago to centralize these and make them dynamic, i.e. to add a new market all we should have to do is to extend an enum. Have a look at `constants.ts` to see what we already have and use those to generalize these.

2022-02-17 15:29 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/graphql/edit-template-message.graphql
> +}
Put these in a tag with the hook instead of its own file

2022-02-17 15:29 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/graphql/get-template-messages.graphql
> +}
Same here

2022-02-17 15:30 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/use-template-messages.tsx
> +}
❌ Have a look at `constants.ts` instead and have a chat with Vladimir if you guys should reconsider this approach. Maybe use already existing locales instead of defining a new enum `Language`?

2022-02-17 15:31 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/use-template-messages.tsx
> +        refetchQueries: () => ['GetTemplateMessages'],
❌ Optimistic response and/or cache manipulations instead

2022-02-17 15:31 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/use-template-messages.tsx
> +        loading: 'Pinning template',
❌ Optimistic response and/or cache manipulations instead

2022-02-17 15:32 UTC, rasmusguterstam commented on src/portals/hope/pages/tools/TemplateMessagesPage.tsx
> +    useState<TemplateMessages | null>(null)
```suggestion
  const [selectedTemplates, setSelectedTemplates] =
    useState<TemplateMessages | null>(null)
```

Or why is the data type in plural?

2022-02-17 15:33 UTC, rasmusguterstam commented on src/portals/hope/pages/tools/TemplateMessagesPage.tsx
> +    useState<TemplateMessages | null>(null)
Or maybe it should be `selectedTemplateMessages`..?

2022-02-17 15:34 UTC, rasmusguterstam commented on src/portals/hope/pages/tools/TemplateMessagesPage.tsx
> +            },
Make this dynamic using our Market enum

2022-02-17 15:36 UTC, rasmusguterstam requested changes
Yeah as you mentioned, you and Vladimir should have a look at the `Language` enum again and reconsider if it's _really_ necessary. We already have locales, those could most likely be used here as well.

2022-02-18 04:39 UTC, maxplt commented on src/portals/hope/features/template-messages/components/TemplateForm.tsx
> +          language: 'ENGLISH',
Here I set `'ENGLISH'` because in `use-template-messages` before creating I replace it by `enum` (`'ENGLISH' = 'EN'`)

2022-02-18 04:43 UTC, maxplt commented on src/portals/hope/features/template-messages/components/TemplateForm.tsx
> +    })
Fields of different messages have names `name="message-SWEDEN"`, `name="message-DENMARK"`, etc.. (postfix is an element of `Market` `enum`)
And here happens enumeration by `Market` `enum` and getting values from needed field

2022-02-18 06:37 UTC, maxplt commented on src/portals/hope/features/template-messages/use-template-messages.tsx
> +        refetchQueries: () => ['GetTemplateMessages'],
How can I do optimistic response during creating? **ID** comes from the backend

2022-02-28 08:15 UTC, rasmusguterstam commented on shared/@hedvig-ui/TextDatePicker/index.tsx
> +    if (minDate && newDate.valueOf() < minDate.valueOf() - 86400000) {
What's happening here? 😳

2022-02-28 08:16 UTC, rasmusguterstam commented on shared/@hedvig-ui/TextDatePicker/index.tsx
> +      return
Why can't we just do a comparison with the actual dates instead of `formattedDate`..?

2022-02-28 08:20 UTC, maxplt commented on shared/@hedvig-ui/TextDatePicker/index.tsx
> +    if (minDate && newDate.valueOf() < minDate.valueOf() - 86400000) {
Date comparison 😅

2022-02-28 08:22 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +  const getSearchTemplate = (searchText: string) =>
Maybe?

```suggestion
  const searchTemplate = (searchText: string) =>
```

2022-02-28 08:26 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +  useEffect(() => {
I'm thinking that, since we have about ~200 lines of logic in this component, maybe we could extract almost all of this into a hook? Especially since we want the same logic inside the chat, not only with conversations?

2022-02-28 08:28 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +  useEffect(() => {
Or in some way put this logic inside `useTemplateMessages`, that would probably be most convenient

2022-02-28 08:30 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/member/MemberSummary.tsx
> +    setLocale((data?.member?.pickedLocale as PickedLocale) || PickedLocale.SvSe)
Probably not an issue, but this would make it cast `undefined` to `PickedLocale` - this should be more correct
```suggestion
    setLocale((data?.member?.pickedLocale || PickedLocale.SvSe) as PickedLocale)
```

2022-02-28 08:31 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +// `
🤓

2022-02-28 08:31 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +  // )
🤓

2022-02-28 08:32 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +
🤪

2022-02-28 08:32 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +    }, 350)
Sweet!

2022-02-28 08:32 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +  // }
🤪

2022-02-28 08:32 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +                //     )?.message || ''
🤪

2022-02-28 08:33 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +      </Bottom> */}
🤪

2022-02-28 08:35 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +}
Very good example of a clear and clean interface, making it very easy to understand what to expect!

2022-02-28 08:35 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +                // Don't work useConfirmDialog in some reason
Hm weird

2022-02-28 08:39 UTC, rasmusguterstam commented on src/portals/hope/features/template-messages/use-template-messages.tsx
> +import React, { createContext, useContext, useState } from 'react'
Even though this file is very large (which it has to be, considering the amount of things going on), I think you've done a really great job here! 🌟 It's very easy to get a grip of what's going on

2022-02-28 08:39 UTC, rasmusguterstam approved these changes
Some minor comments but overall great job! 🚀

2022-02-28 08:40 UTC, rasmusguterstam commented on shared/@hedvig-ui/TextDatePicker/index.tsx
> +    if (minDate && newDate.valueOf() < minDate.valueOf() - 86400000) {
Yeah but why `86400000`?!

2022-02-28 09:13 UTC, maxplt commented on src/portals/hope/features/template-messages/components/TemplateMessagesModal.tsx
> +
@rasmusguterstam 
It's commented because at the moment I'm not sure in which way I need to switch language with new backend logic.
I'll uncomment and update it after I'll be able to test the backend locally and be sure how to switch it.

2022-03-02 15:54 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +  )
Nice!

2022-03-02 15:55 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/chat/ConversationChat.tsx
> +            )}
Why not 
```suggestion
            {hinting && (
              <HintText>
                {templateHint?.title ? `/${templateHint?.title}` : message}
              </HintText>
            )}
```

2022-03-02 15:56 UTC, rasmusguterstam commented on src/portals/hope/features/conversations/member/MemberSummary.tsx
> +  }, [memberId])
If this is how we're using it, why not have it directly in the constructor, e.g. something like 

```typescript
const { setLocale } = useTemplateMessages(memberId)
```

2022-03-02 16:07 UTC, rasmusguterstam approved these changes
Considering the diff is ~2.1k lines and we're at 75 comments, I can't realistically give you more feedback or say yay or nay - we'll just have to deploy this and see what happens 😅 

A classic LGTM on this one ✅

2022-03-04 06:58 UTC, merged