Fix: Keyboard navigation
HedvigInsurance/hedgehog pull request #589
Opened 2022-03-10 04:50 UTC by maxplt

# Jira Issue: [IP-262](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-262)

## What?
Fix some issues and did some refactor:
*  `TopBar`: focus back on `notificationsButton` on modal closing by _**Escape**_
* Implement `use-navigation` inside `Questions` and make `Questions` more clear. 
* Questions: press enter to focus on textarea
  + Remove `use-hook-form` to come it true.
* Border bouncing. Fixed by _transparent_ border when no focus
* Fix issue when first listing item at lists not opening by Enter
* `Claims filters`: when hit _Enter_ stay focused at the filter group
* Re-rendring of Dashborad
  + By moving `Metrics` in other component

But I still have some stuff that I didn't resolve yet:
* Focus on the currently active or last visited item, but not the first child of the list/group (filters/sidebar items/tabs)
  + Not sure how to make it. Because **registration fields of navigation** don't update and always constant.
* Found other issue: on changing `claims filters` by navigation (_Enter_) they behave strangely. I think the reason is the same with previous issue

## Why?
For convenient keyboard navigation

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2022-03-11 10:22 UTC, rasmusguterstam requested changes

2022-03-11 10:22 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimFiles/FileUpload.tsx
> +
Sorry for being a pain here, but this is basically reintroducing the same pattern we completely reverted before. It's basically a question of component responsibility, where I see this as a _very_ slippery slope where a lot of different components from completely different features or parts of the application should explicitly respect the navigation feature by passing, reacting to and managing different focus states. 

That's why I tried playing around with centralizing this with the navigation context, where you basically "inject" with the context hook and are provided a nice interface (e.g. just spreading components) and things just work as expected. That's also why I decided to keep the `focus` state internal to the navigation context - as a developer, you should never care about what is currently being focused and not, and if you do, you should do that internally within the navigation context. I noticed that you exposed that state in a feature a while ago (i.e. being able to do something like `const { cursor } = useNavigation()`), and I let that slide to see if we were on to something, but the more I think about it I believe we should keep the `focus` / `cursor` state internally within the context and that it's a pretty good rule of thumb to keep it that way. 

This comment is not just for this piece of code, but basically the entire PR. Sorry that I can't give you an exact way to do this, but I can't help thinking that if we were to just move ahead with this, it will: (1) never be used (2) we'll slowly lose keyboard coverage over time since no one will maintain this and (3) developers will just be annoyed since they have to understand how it works, instead of just using a nice interface.

2022-03-15 11:22 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +          />
I like it and it's clean, but what about trying to navigate between these using tab index instead?

2022-03-15 11:23 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +                },
What 😅

2022-03-15 11:25 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +                    : 'Contract for Claim',
Not sure exactly how this would work, but what one could specify a list of strings instead and `useNavigation` tries them in that order?

So something like this, where it will move on to the next one if the other one isn't registered?

```typescript
up: ['Terms And Conditions', 'Contract for Claim']
```

2022-03-15 11:25 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +                    : 'Contract for Claim',
Thoughts?

2022-03-15 11:29 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-templates/CreateFilterModal.tsx
> +  }, [])
This is clean, but would it be possible to integrate similar logic within the `register` hook? The on-mount should be easy to fix, and the un-mount could maybe be just the parent? So when the component is un-mounted _or_ Escape is pressed, it will take you to `parent`? Thoughts?

2022-03-15 11:39 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claims-list/filters/ClaimListFilters.tsx
>            })
In scenarios like these, it would be really cool if we could have something like `registerList` which given a list and a name will do this repetetive logic behind the scenes. maybe something like


```typescript

const { registerList } = useNavigation()

const { registerListItem } = registerList(
    range(numberMemberGroups),  // The list
    'MemberGroups',  // Namespace for the list items
    'MemberMarket',  // If we reach the bottom, where do we go?
    'SearchInput',    // If we reach the top, where do we go?
    (group) => console.log(group) // What do we do when we resolve the list item?
)

...

range(numberMemberGroups).map((filterNumber, index) => {
    return <SomeComponent {...registerListItem()} />
}


```

2022-03-15 11:41 UTC, rasmusguterstam requested changes
Much better! Added some suggestions and some questions, would love to get your thoughts on all of it 😄

2022-03-15 11:45 UTC, maxplt commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +                    : 'Contract for Claim',
Fully agree. Will try!

2022-03-15 11:47 UTC, maxplt commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +          />
Yeah, sure. At the moment purpose is to find a right way for items focusing.

2022-03-15 11:48 UTC, maxplt commented on src/portals/hope/features/claims/claim-templates/CreateFilterModal.tsx
> +  }, [])
Nice point! I'm now trying to integrate this one inside `use-navigation` hook. No success at the moment :(

2022-03-16 13:42 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +                    : 'Contract for Claim',
@maxplt Any progress on this?

2022-03-16 13:44 UTC, rasmusguterstam commented on src/portals/hope/features/navigation/sidebar/VerticalMenu.tsx
> +    },
What is this and why do we need it? 😮

2022-03-16 13:50 UTC, maxplt commented on src/portals/hope/features/navigation/sidebar/VerticalMenu.tsx
> +    },
For the "focus on the currently active or last visited item"

2022-03-17 08:28 UTC, maxplt commented on src/portals/hope/features/navigation/sidebar/VerticalMenu.tsx
> +    },
We need it for focusing on active item

2022-03-17 08:36 UTC, maxplt commented on src/portals/hope/features/claims/claim-details/ClaimInformation/ClaimInformation.tsx
> +                    : 'Contract for Claim',
Made it in last commit. But at the moment it looks a little bit weird

2022-03-18 08:01 UTC, maxplt commented on src/portals/hope/features/claims/claim-details/ClaimPayments/components/ClaimPaymentForm.tsx
> +            { width: '8rem', marginBottom: '1.5rem' },
Yeah. But we need it to specify styles for navigation items, because some of them looks weird without these styles. And I can't find any better solution at the moment.

2022-03-30 09:26 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +  function registerList<T>({
How come `function` here??

2022-03-30 09:26 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +    nameField: keyof T
🌟

2022-03-30 09:28 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimFiles/FileUpload.tsx
> +            <Button {...getRootProps()} {...register('Claim File Input', {})}>
Do we need an empty json here? Shouldn't that just be default if we don't specify anything?

2022-03-30 09:30 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/components/ClaimOutcomeDropdown.tsx
> +}> = ({ claimId, ...props }) => {
I guess this works, but maybe we should extend it with the `DropdownProps` as well to be clear? So something like

```typescript
React.FC<{ claimId: string } & Omit<DropdownProps, 'placeholder'>>
```

2022-03-30 09:30 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/components/ClaimOutcomeDropdown.tsx
> +}> = ({ claimId, ...props }) => {
For all of these dropdowns ofc

2022-03-30 09:34 UTC, rasmusguterstam commented on src/portals/hope/features/members-search/components/SearchForm.tsx
> +                withFocus: true,
What's the difference? 🤓

2022-03-30 09:39 UTC, rasmusguterstam commented on src/portals/hope/features/questions/questions-list/QuestionGroupItem.tsx
> +  const ref = forwardRef ?? internalRef
🤝

2022-03-30 09:41 UTC, rasmusguterstam commented on src/portals/hope/pages/claims/ClaimDetailsPage.tsx
> +                  focusTarget: 'Claim Status',
Is this what happens when you press the focus key, in this case `ctrl + 2`? Because `withFocus` I guess is implied by `focusTarget` being defined, and also why isn't the `Claim Status` responsible for this logic instead of the `Claim Card #2`?

2022-03-30 09:42 UTC, rasmusguterstam commented on src/portals/hope/pages/claims/ClaimDetailsPage.tsx
> +                  focusTarget: 'Claim Status',
Is it because you still want the card styled?

2022-03-30 09:42 UTC, rasmusguterstam requested changes
Very close now, but some questions!

2022-03-31 05:08 UTC, maxplt commented on src/portals/hope/features/claims/claim-details/ClaimInformation/components/ClaimOutcomeDropdown.tsx
> +}> = ({ claimId, ...props }) => {
I think I can remove this from changed dropdowns. Since we will use Tab navigation instead of keyboard.

2022-03-31 05:16 UTC, maxplt commented on src/portals/hope/features/members-search/components/SearchForm.tsx
> +                withFocus: true,
`autoFocus` - for do automatic **focus** via `useNavigation` on mount
`withFocus` (+ `focusTarget`) - for doing exactly **focus** to the `focusTarget` item (`.focus()`)

2022-03-31 05:21 UTC, maxplt commented on src/portals/hope/pages/claims/ClaimDetailsPage.tsx
> +                  focusTarget: 'Claim Status',
If there is no `focusTarget` but has `withFocus` - `true`, it'll be **focused** on the **current** item instead of the **target**.

2022-03-31 05:24 UTC, maxplt commented on src/portals/hope/pages/claims/ClaimDetailsPage.tsx
> +                  focusTarget: 'Claim Status',
Used `Claim Card #2` for this purpose because we don't need to use keyboard navigation inside cards (we use tab navigation).
And yes, for some styles. You press `Ctrl + 2` and see, that you are focused on the Card. Then you press `Enter` and get focus on `Claim Status`

2022-03-31 08:20 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimInformation/components/ClaimOutcomeDropdown.tsx
> +}> = ({ claimId, ...props }) => {
Yeah good point!

2022-03-31 08:25 UTC, rasmusguterstam commented on src/portals/hope/features/members-search/components/SearchForm.tsx
> +                withFocus: true,
Alright maybe clarify by renaming to `withFocusTarget` or something?

2022-03-31 08:27 UTC, rasmusguterstam commented on src/portals/hope/pages/claims/ClaimDetailsPage.tsx
> +                  focusTarget: 'Claim Status',
Ah alright! Maybe split these up and have `focusTarget: string` and another, `focusOnElement` or something like that, so you know what to expect. If `focusTarget` is specified, it is implied that `withFocus` is true so that's just redundant

2022-03-31 08:30 UTC, rasmusguterstam commented on src/portals/hope/features/navigation/sidebar/VerticalMenu.tsx
> +    },
Hm do we really need this? Why can't it just keep track of the list in the order we register them? Should be possible to generify this logic behind the scenes

2022-03-31 08:37 UTC, rasmusguterstam commented on src/portals/hope/features/questions/questions-list/FilteredQuestionGroups.tsx
> +          })}
`registerList`?

2022-03-31 08:37 UTC, rasmusguterstam commented on src/portals/hope/features/user/notifications/NotificationsModal.tsx
>    }, [])
❌

2022-03-31 08:37 UTC, rasmusguterstam commented on src/portals/hope/features/user/notifications/NotificationsModal.tsx
>    }, [])
No explicit focus and/or leakage of `cursor` state (just remove them from the hook I guess)

2022-03-31 08:40 UTC, rasmusguterstam commented on src/portals/hope/pages/claims/ClaimDetailsPage.tsx
> +                )}
Ah I see the point of `focusTarget` now! That's nice. I mentioned it in another comment, but `withFocus` is redundant here. And the double styles feels really weird, but I guess it's fine for now!

2022-03-31 08:40 UTC, rasmusguterstam requested changes
😄

2022-04-01 04:32 UTC, maxplt commented on src/portals/hope/features/navigation/sidebar/VerticalMenu.tsx
> +    },
Behind the scenes, hook can't track the current situation. I didn't find a way of updating outside states. Like, inside hook we always have only the initial state.
This is the only way I found to recognize the changes.

2022-04-01 06:15 UTC, maxplt commented on src/portals/hope/features/members-search/components/SearchForm.tsx
> +                withFocus: true,
But it is not exactly only for the target. If an item has no **target**, it'll be **focused** on the current item (if `withFocus` is `true`)

2022-04-07 12:12 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +          : ''
Hehe I see what you're doing, but simplify this into different lines and provide some explanatory names to make it easier to understand

2022-04-07 12:13 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +          : ''
🤪

2022-04-07 12:13 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +          : ''
🥴

2022-04-07 12:17 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +        })
Sweeet!! 🌟

2022-04-07 12:17 UTC, rasmusguterstam commented on shared/@hedvig-ui/hooks/navigation/use-navigation.tsx
> +        })
Skip for now, but makes it very easy to add a horizontal equivalent! 🤓

2022-04-07 12:19 UTC, rasmusguterstam commented on src/portals/hope/features/dashboard/MetricList.tsx
> +          )
Or you know what, maybe it's actually worth adding the same thing as a vertical list but horizontally as well - would simplify this a lot, right?

2022-04-08 05:00 UTC, maxplt commented on src/portals/hope/features/navigation/sidebar/VerticalMenu.tsx
> +    },
@rasmusguterstam 
I mean that we can't do like this:
```
const navigation = register(item.title, {
   focus: index === 0 || pathname === item.title ? Keys.S : undefined,
   resolve: () => {
      tem.hotkeyHandler()
   }
   // ...
}
```
Because it saves only the path, that was on mounting. And it'll not be changed on redirections.
And in this way that provides `focusCondition` we achieve this.

2022-04-11 06:17 UTC, rasmusguterstam commented on src/portals/hope/features/dashboard/MetricList.tsx
> +              <span>Filtered Claim Template</span>
Sweeet! 🌟

2022-04-11 06:17 UTC, rasmusguterstam commented on src/portals/hope/features/members-search/components/SearchForm.tsx
> +              // id="query"
Remove if unused

2022-04-11 06:19 UTC, rasmusguterstam commented on src/portals/hope/features/navigation/topbar/TopBar.tsx
> +          }
Why do we have to do like this just here?

2022-04-11 06:20 UTC, rasmusguterstam approved these changes

2022-04-11 09:43 UTC, merged