Update: Keyboard navigation
HedvigInsurance/hedgehog pull request #633
Opened 2022-04-12 05:36 UTC by maxplt

# Jira Issue: []

## What?
Make some additional fixes and improvements to keyboard navigation:
* Fix navigation styles in tables
* Add navigation to new Search

## Why?
-

## Optional screenshots

## Optional checklist
- [ ] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2022-04-12 07:56 UTC, rasmusguterstam commented on shared/@hedvig-ui/Table/table.tsx
> +            },
How come we're not using the `registerList` here?

2022-04-12 07:57 UTC, rasmusguterstam commented on src/portals/hope/features/search/members/MemberSearch.tsx
> +              )
`registerList`

2022-04-12 07:57 UTC, rasmusguterstam requested changes
Let's use the `registerList`!

2022-04-12 08:23 UTC, maxplt commented on shared/@hedvig-ui/Table/table.tsx
> +            },
I afraid that I can't use `registerList` here
Because it's just separate `TableRow`.
If we want `registerList`, we need to do it outside the table in component, that use this table

2022-04-13 09:07 UTC, rasmusguterstam commented on shared/@hedvig-ui/Table/table.tsx
> +            },
Not sure I follow, but yeah I know that we can't use `registerList` on this exact component - but why don't we use `registerList` outside and the `register` function it provides here instead?

2022-04-13 09:10 UTC, rasmusguterstam commented on src/portals/hope/features/search/members/MemberSearch.tsx
> +                  ...member,
Why do we spread this one? 🤔

2022-04-13 09:10 UTC, rasmusguterstam commented on src/portals/hope/features/claims/claim-details/ClaimType/ClaimType.tsx
> +              inputId="claim-type-dropdown"
I guess this is just a specific fix for searchable dropdowns?

2022-04-13 09:10 UTC, rasmusguterstam commented on src/portals/hope/features/search/members/MemberSearch.tsx
> +    },
Very nice!

2022-04-13 09:11 UTC, rasmusguterstam requested changes
Some questions!

2022-04-13 09:30 UTC, maxplt commented on src/portals/hope/features/claims/claim-details/ClaimType/ClaimType.tsx
> +              inputId="claim-type-dropdown"
Yes! For doing focus inside input that is in the dropdown (by id)

2022-04-13 09:33 UTC, maxplt commented on src/portals/hope/features/search/members/MemberSearch.tsx
> +                  ...member,
Because I add to the member item the name of Row - `name: 'Table Row ${member. hit.id}'`

2022-04-13 09:37 UTC, maxplt commented on shared/@hedvig-ui/Table/table.tsx
> +            },
But we have lots of components with Tables
I thought that it's more comfortable to specify navigation here once instead of many times in all components

2022-04-13 10:54 UTC, rasmusguterstam commented on shared/@hedvig-ui/Table/table.tsx
> +            },
What if we have 2 tables in the same page though?

2022-04-13 11:15 UTC, maxplt commented on shared/@hedvig-ui/Table/table.tsx
> +            },
Hm, it's pretty complex issue
Maybe remove `autoFocus` from one table and add moving between tables by edges

2022-04-19 07:42 UTC, vonElfvin approved these changes
💯

2022-04-19 12:16 UTC, merged