Add ManyPets fields on Agreements tab
HedvigInsurance/hedgehog pull request #978
Opened 2023-05-17 15:00 UTC by fredriklagerblad

# Jira Issue: [CLX-XXX]

## What?
-

## Why?
-

## If applicable, rooms for improvement?
- 

## Optional screenshots

## Optional checklist
- [ ] Codescouted
- [ ] Unit tests written
- [ ] Tested locally

2023-05-17 15:25 UTC, AlexSJ1990 approved these changes
Lovely :) but there are some linting issues

2023-05-17 15:28 UTC, meletios requested changes
Can you fix the linting Mr Frontender?

2023-05-22 09:21 UTC, meletios approved these changes

2023-05-22 12:12 UTC, falklinus approved these changes

2023-05-22 12:12 UTC, falklinus commented on src/portals/hope/features/member/tabs/contracts-tab/agreement/AgreementInfo.tsx
> +              .join(', ')}
Clever 😄

2023-05-23 07:11 UTC, merged